Repository explodinggradients/ragas, pull requests merged in 2024-05, with the labels that each got.

#970 answer-correctness : fix edge cases
  src/ragas/metrics/_answer_correctness.py
Labels: size:M

#972 Fix ensembler : handle edge cases
  src/ragas/metrics/_context_precision.py
  src/ragas/metrics/_context_recall.py
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/base.py
Labels: size:M

#973 feat: adding new defaults to openai Model and embeddings
  .github/workflows/ci.yaml
  docs/howtos/customisations/gcp-vertexai.ipynb
  docs/howtos/integrations/langfuse.ipynb
  src/ragas/embeddings/base.py
  src/ragas/llms/base.py
  src/ragas/testset/generator.py
  tests/benchmarks/benchmark_eval.py
Labels: size:M

#974 Improve grammar and punctuation in critique prompts: addresses #971
  src/ragas/metrics/critique.py
Labels: size:S

#976 feat: Ragas CI/CD
  docs/getstarted/index.md
  docs/howtos/applications/add_to_ci.md
  docs/howtos/applications/data_preparation.md
  docs/howtos/applications/index.md
  src/ragas/_analytics.py
  src/ragas/evaluation.py
  src/ragas/metrics/base.py
  tests/conftest.py
  tests/e2e/test_amnesty_in_ci.py
  tests/unit/test_analytics.py
Labels: size:L

#980 fix: patch type issue in evolution parsing
  src/ragas/testset/evolutions.py
Labels: size:XS

#987 Additions to community contributed articles
  docs/community/index.md
  docs/concepts/metrics/answer_relevance.md
Labels: size:XS

#988 docs: update ragas_custom_model.ipynb
  docs/howtos/customisations/ragas_custom_model.ipynb
Labels: size:XS
