Repository explodinggradients/ragas, pull requests merged in 2024-09, with the labels that each got.

#1235 load HHEM on specified device
  src/ragas/metrics/_faithfulness.py
Labels: size:S

#1232 feat: new Prompt object and faithfulness metric
  .gitignore
  src/experimental/ragas_experimental/llms/prompt.py
  src/experimental/ragas_experimental/metrics/__init__.py
  src/experimental/ragas_experimental/metrics/_faithfulness.py
  src/experimental/tests/test_prompt.py
  src/ragas/llms/base.py
  src/ragas/metrics/_faithfulness.py
Labels: size:L

#1240 feat (experimental) added new prompt and metric into `ragas.experimental`
  src/experimental/tests/test_prompt.py
  src/ragas/experimental/llms/__init__.py
  src/ragas/experimental/llms/prompt.py
  src/ragas/experimental/metrics/__init__.py
  src/ragas/experimental/metrics/_faithfulness.py
  src/ragas/llms/base.py
Labels: size:M

#1242 update documentation for faithfulness with HHEM
  docs/concepts/metrics/faithfulness.md
Labels: size:XS

#1222 New data representation
  src/ragas/dataset_schema.py
  src/ragas/evaluation.py
  src/ragas/experimental/metrics/_faithfulness.py
  src/ragas/integrations/langchain.py
  src/ragas/integrations/llama_index.py
  src/ragas/messages.py
  src/ragas/metrics/__init__.py
  src/ragas/metrics/_answer_correctness.py
  src/ragas/metrics/_answer_relevance.py
  src/ragas/metrics/_answer_similarity.py
  src/ragas/metrics/_context_entities_recall.py
  src/ragas/metrics/_context_precision.py
  src/ragas/metrics/_context_recall.py
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/_noise_sensitivity.py
  src/ragas/metrics/_rubrics_based.py
  src/ragas/metrics/_summarization.py
  src/ragas/metrics/base.py
  src/ragas/metrics/critique.py
  src/ragas/metrics/utils.py
  src/ragas/utils.py
  src/ragas/validation.py
  tests/unit/test_database_schema.py
  tests/unit/test_executor_in_jupyter.ipynb
  tests/unit/test_metric.py
  tests/unit/test_validation.py
Labels: size:XXL

#1256 Feat: Opik Integration
  docs/getstarted/monitoring.md
  docs/howtos/applications/tracing.md
  docs/howtos/integrations/index.md
  docs/howtos/integrations/opik.ipynb
  src/ragas/evaluation.py
  src/ragas/integrations/opik.py
Labels: size:L

#1249 Add support to MultiTurn Metrics
  docs/concepts/metrics/rubrics_based.md
  src/ragas/evaluation.py
  src/ragas/experimental/llms/prompt.py
  src/ragas/experimental/metrics/_faithfulness.py
  src/ragas/integrations/langchain.py
  src/ragas/metrics/__init__.py
  src/ragas/metrics/_answer_correctness.py
  src/ragas/metrics/_answer_relevance.py
  src/ragas/metrics/_answer_similarity.py
  src/ragas/metrics/_context_entities_recall.py
  src/ragas/metrics/_context_precision.py
  src/ragas/metrics/_context_recall.py
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/_noise_sensitivity.py
  src/ragas/metrics/_rubrics_based.py
  src/ragas/metrics/_summarization.py
  src/ragas/metrics/base.py
  src/ragas/metrics/critique.py
  src/ragas/metrics/domain_specific_rubrics/__init__.py
  src/ragas/metrics/domain_specific_rubrics/with_reference.py
  src/ragas/metrics/domain_specific_rubrics/without_reference.py
  src/ragas/utils.py
  src/ragas/validation.py
  tests/unit/test_metric.py
  tests/unit/test_validation.py
Labels: size:XL

#1261 fix: add single_turn_ascore
  src/ragas/experimental/metrics/_faithfulness.py
Labels: size:XS

#1262 fix: handle v0.1 dataset
  src/ragas/evaluation.py
  src/ragas/metrics/_answer_relevance.py
Labels: size:S

#1259 feat: set and get prompts for metrics
  .github/workflows/ci.yaml
  docs/howtos/integrations/opik.ipynb
  src/ragas/integrations/opik.py
  src/ragas/metrics/base.py
Labels: size:M

#1267 fix: inverse distance
  src/ragas/metrics/_string.py
Labels: size:XS

#1268 fix: non llm based metrics
  src/ragas/metrics/_bleu_score.py
  src/ragas/metrics/_string.py
Labels: size:M

#1275 fix: v1 to v2 dataset
  src/ragas/evaluation.py
  src/ragas/utils.py
Labels: size:S

#1276 fix: make score nested if loop_is_running
  src/ragas/metrics/base.py
Labels: size:S

#1266 feat: add non llm based context recall
  docs/concepts/metrics/context_recall_v2.md
  src/ragas/metrics/_context_recall.py
Labels: size:L

#1264 feat: Non LLM based context precision
  docs/concepts/metrics/context_precision_v2.md
  src/ragas/metrics/_context_precision.py
Labels: size:L

#1281 feat: added n and temperature passthrough to prompt
  src/ragas/experimental/llms/prompt.py
  src/ragas/experimental/metrics/_faithfulness.py
  src/ragas/metrics/domain_specific_rubrics/with_reference.py
  src/ragas/metrics/domain_specific_rubrics/without_reference.py
Labels: size:M

#1279 Add option to disable progress bar in `evaluate`
  src/ragas/evaluation.py
  src/ragas/executor.py
Labels: size:XS

#1286 feat: new aspect critic metrics
  docs/concepts/metrics/aspect_critic.md
  docs/concepts/metrics/index.md
  src/ragas/evaluation.py
  src/ragas/metrics/__init__.py
  src/ragas/metrics/_aspect_critic.py
  src/ragas/metrics/critique.py
  tests/unit/test_import.py
  tests/unit/test_metric.py
  tests/unit/test_simple.py
Labels: size:L

#1291 feat: add simple scorer metric
  src/ragas/metrics/_simple_criteria.py
Labels: size:L

#1300 Fix wrong input key name
  src/ragas/experimental/metrics/_faithfulness.py
  src/ragas/metrics/_context_precision.py
Labels: size:XS

#1287 chore: move rubrics based metric into single file
  src/ragas/metrics/__init__.py
  src/ragas/metrics/_domain_specific_rubrics.py
  src/ragas/metrics/base.py
  src/ragas/metrics/domain_specific_rubrics/__init__.py
  src/ragas/metrics/domain_specific_rubrics/without_reference.py
Labels: size:L

#1304 feat: Instance specifc rubrics metrics
  src/ragas/dataset_schema.py
  src/ragas/metrics/_instance_specific_rubrics.py
Labels: size:L

#1303 feat: agent goal accuracy metric
  src/ragas/metrics/_goal_accuracy.py
Labels: size:L

#1314 docs: agent metrics
  docs/concepts/metrics/agents.md
Labels: size:L

#1295 Update Opik notebook example and integration
  docs/howtos/applications/tracing.md
  docs/howtos/integrations/opik.ipynb
  src/ragas/integrations/opik.py
Labels: size:L

#1324 fix: column rename
  src/ragas/metrics/_noise_sensitivity.py
Labels: size:XS

#1329 fix: pin langchain_core to <3
  pyproject.toml
  src/ragas/integrations/opik.py
Labels: size:XS

#1327 feat: topic adherence metric
  docs/concepts/metrics/topic_adherence.md
  src/ragas/dataset_schema.py
  src/ragas/metrics/_topic_adherence.py
Labels: size:L

#1311 feat: tool call accuracy
  src/ragas/dataset_schema.py
  src/ragas/metrics/_tool_call_accuracy.py
Labels: size:M

#1323 feat: sql sementic equivalence
  docs/concepts/metrics/sql.md
  pyproject.toml
  requirements/dev.txt
  src/ragas/metrics/_datacompy_score.py
  src/ragas/metrics/_sql_semantic_equivalence.py
Labels: size:L

#1334 feat: Factual correctnes metric
  docs/concepts/metrics/factual_correctness.md
  src/ragas/metrics/_factual_correctness.py
Labels: size:L

#1344 feat: Adding transforms for testset generation
  src/ragas/experimental/llms/__init__.py
  src/ragas/experimental/metrics/_faithfulness.py
  src/ragas/experimental/prompt.py
  src/ragas/metrics/_aspect_critic.py
  src/ragas/metrics/_domain_specific_rubrics.py
  src/ragas/metrics/_factual_correctness.py
  src/ragas/metrics/_goal_accuracy.py
  src/ragas/metrics/_instance_specific_rubrics.py
  src/ragas/metrics/_simple_criteria.py
  src/ragas/metrics/_sql_semantic_equivalence.py
  src/ragas/metrics/_topic_adherence.py
  src/ragas/metrics/base.py
Labels: size:M

#1346 docs: traditional metrics
  docs/concepts/metrics/traditional.md
  src/ragas/metrics/_string.py
Labels: size:L

#1345 feat: transforms for Knowledge Graphs
  src/ragas/experimental/testset/graph.py
  src/ragas/experimental/testset/transforms/base.py
  src/ragas/experimental/testset/transforms/extractors/__init__.py
  src/ragas/experimental/testset/transforms/extractors/embeddings.py
  src/ragas/experimental/testset/transforms/extractors/llm_base.py
  src/ragas/experimental/testset/transforms/extractors/regex_based.py
  src/ragas/experimental/testset/transforms/relationship_builders/__init__.py
  src/ragas/experimental/testset/transforms/relationship_builders/cosine.py
  src/ragas/experimental/testset/transforms/splitters/__init__.py
  src/ragas/experimental/testset/transforms/splitters/headline.py
Labels: size:XL

#1347 docs: core concepts in metrics
  docs/concepts/metrics/agents.md
  docs/concepts/metrics/answer_correctness.md
  docs/concepts/metrics/answer_relevance.md
  docs/concepts/metrics/aspect_critic.md
  docs/concepts/metrics/context_entities_recall.md
  docs/concepts/metrics/context_precision.md
  docs/concepts/metrics/context_precision_v2.md
  docs/concepts/metrics/context_recall.md
  docs/concepts/metrics/context_recall_v2.md
  docs/concepts/metrics/context_utilization.md
  docs/concepts/metrics/factual_correctness.md
  docs/concepts/metrics/faithfulness.md
  docs/concepts/metrics/general_purpose.md
  docs/concepts/metrics/index.md
  docs/concepts/metrics/noise_sensitivity.md
  docs/concepts/metrics/semantic_similarity.md
  docs/concepts/metrics/sql.md
  docs/concepts/metrics/summarization_score.md
  docs/concepts/metrics/topic_adherence.md
Labels: size:XL

#1348 chores: cleanup metrics
  src/ragas/metrics/__init__.py
  src/ragas/metrics/_answer_relevance.py
  src/ragas/metrics/_answer_similarity.py
  src/ragas/metrics/_context_entities_recall.py
  src/ragas/metrics/_domain_specific_rubrics.py
  src/ragas/metrics/_factual_correctness.py
  src/ragas/metrics/_noise_sensitivity.py
  src/ragas/metrics/_rogue_score.py
  src/ragas/metrics/_sql_semantic_equivalence.py
  src/ragas/metrics/_tool_call_accuracy.py
Labels: size:L

#1351 docs: refactor core concepts
  docs/concepts/components/index.md
  docs/concepts/evaluation_driven.md
  docs/concepts/index.md
  docs/concepts/test_data_generation/index.md
Labels: size:M

#1350 wrap as_complete with async
  src/ragas/executor.py
  tests/unit/test_executor.py
  tests/unit/test_executor_in_jupyter.ipynb
Labels: size:XS

#1356 chores: add datasets to init
  src/ragas/__init__.py
Labels: size:S

#1355 docs: new getting started
  docs/concepts/metrics/index.md
  docs/getstarted/evaluation.md
  docs/getstarted/index.md
  docs/getstarted/monitoring.md
  docs/getstarted/prepare_data.ipynb
  docs/getstarted/rag_evaluation.md
Labels: size:XL

#1361 docs: metrics concepts
  docs/concepts/metrics/index.md
Labels: size:M

#1362 docs: add mindmap
  docs/_static/imgs/metrics_mindmap.png
  docs/concepts/metrics/index.md
Labels: size:XS

#1363 Fixed Nav, search, and some styling issues for the docs
  docs/extra/style.css
Labels: size:S

#1352 feat: transform engine to execute transforms
  pyproject.toml
  src/ragas/executor.py
  src/ragas/experimental/__init__.py
  src/ragas/experimental/testset/__init__.py
  src/ragas/experimental/testset/generators/__init__.py
  src/ragas/experimental/testset/transforms/__init__.py
  src/ragas/experimental/testset/transforms/base.py
  src/ragas/experimental/testset/transforms/engine.py
  src/ragas/experimental/testset/transforms/extractors/__init__.py
  src/ragas/experimental/testset/transforms/extractors/llm_based.py
  src/ragas/experimental/testset/transforms/splitters/__init__.py
Labels: size:L

#1369 chores: remove fuzzywuzzy
  pyproject.toml
  requirements/dev.txt
  src/experimental/ragas_experimental/testset/relationships/similarity.py
Labels: size:XS

#1365 docs: component guides
  docs/concepts/components/eval_dataset.md
  docs/concepts/components/eval_sample.md
  docs/concepts/components/index.md
  docs/concepts/components/prompt.md
Labels: size:L

#1370 chores: fix typo
  docs/concepts/metrics/faithfulness.md
  src/ragas/metrics/__init__.py
  src/ragas/metrics/_faithfulness.py
Labels: size:S

#1371 fix:ensure correct sequence in tool calls
  docs/concepts/metrics/agents.md
  src/ragas/metrics/_tool_call_accuracy.py
Labels: size:M

#1368 [howtos] update Langfuse cookbook
  docs/howtos/integrations/langfuse.ipynb
Labels: size:L

#1359 feat: adding an implementation of abstractQA
  docs/howtos/integrations/helicone.ipynb
  src/experimental/ragas_experimental/testset/generators/base.py
  src/experimental/ragas_experimental/testset/questions/base.py
  src/ragas/executor.py
  src/ragas/experimental/prompt.py
  src/ragas/experimental/testset/generators/__init__.py
  src/ragas/experimental/testset/generators/abstract.py
  src/ragas/experimental/testset/generators/base.py
  src/ragas/experimental/testset/generators/prompts.py
  src/ragas/experimental/testset/transforms/engine.py
  src/ragas/experimental/testset/transforms/relationship_builders/__init__.py
  src/ragas/integrations/langchain.py
  src/ragas/integrations/opik.py
  src/ragas/llms/base.py
  src/ragas/metrics/_context_precision.py
  src/ragas/metrics/_context_recall.py
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/_topic_adherence.py
  src/ragas/testset/docstore.py
  src/ragas/testset/evolutions.py
  src/ragas/testset/extractor.py
Labels: size:XL

#1375 feat: implement `TestsetGenerator`
  docs/howtos/integrations/langfuse.ipynb
  docs/references/testset_generation.md
  mkdocs.yml
  src/ragas/dataset_schema.py
  src/ragas/experimental/testset/__init__.py
  src/ragas/experimental/testset/generators/__init__.py
  src/ragas/experimental/testset/generators/abstract.py
  src/ragas/experimental/testset/generators/base.py
  src/ragas/experimental/testset/generators/generator.py
  src/ragas/experimental/testset/generators/utils.py
  src/ragas/experimental/testset/graph.py
  src/ragas/experimental/testset/transforms/__init__.py
  src/ragas/experimental/testset/transforms/base.py
  src/ragas/experimental/testset/transforms/engine.py
  src/ragas/experimental/testset/transforms/splitters/headline.py
  src/ragas/integrations/opik.py
  src/ragas/metrics/__init__.py
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/_tool_call_accuracy.py
Labels: size:L

#1373 docs: testset generation
  docs/_static/imgs/kg_rag.png
  docs/_static/imgs/metrics_mindmap.png
  docs/concepts/index.md
  docs/concepts/test_data_generation/index.md
  docs/concepts/test_data_generation/rag.md
  docs/getstarted/index.md
  docs/getstarted/rag_testset_generation.ipynb
  docs/getstarted/testset_generation.md
Labels: size:L

#1376 feat: added more simulators
  docs/references/testset_generation.md
  src/ragas/dataset_schema.py
  src/ragas/experimental/prompt.py
  src/ragas/experimental/testset/__init__.py
  src/ragas/experimental/testset/generators/__init__.py
  src/ragas/experimental/testset/generators/abstract.py
  src/ragas/experimental/testset/simulators/__init__.py
  src/ragas/experimental/testset/simulators/abstract_qa.py
  src/ragas/experimental/testset/simulators/base.py
  src/ragas/experimental/testset/simulators/base_qa.py
  src/ragas/experimental/testset/simulators/generate.py
  src/ragas/experimental/testset/simulators/prompts.py
  src/ragas/experimental/testset/simulators/specific_qa.py
  src/ragas/experimental/testset/simulators/utils.py
  src/ragas/experimental/testset/transforms/__init__.py
  src/ragas/experimental/testset/transforms/base.py
  src/ragas/experimental/testset/transforms/engine.py
  src/ragas/experimental/testset/transforms/extractors/embeddings.py
  src/ragas/experimental/testset/transforms/relationship_builders/cosine.py
  src/ragas/messages.py
  tests/unit/test_database_schema.py
  tests/unit/test_validation.py
Labels: size:XXL

#1380 Update models in Ragas documentation: change gpt-3.5-turbo-16k to gpt-4o-mini and gpt-4 to gpt-4o
  docs/concepts/testset_generation.md
  docs/howtos/applications/compare_embeddings.md
  docs/howtos/applications/compare_llms.md
  docs/howtos/applications/use_prompt_adaptation.md
Labels: size:S

#1382 fix: aspect_critique documentation
  docs/concepts/metrics/general_purpose.md
Labels: size:S

#1384 docs: added google analytics to mkdocs
  mkdocs.yml
  pyproject.toml
Labels: size:S

#1388 docs: fix index for metric/index.md
  docs/concepts/metrics/index.md
Labels: size:S

#1366 fix: fixed verdict comparison in evolutions.py
  src/ragas/testset/evolutions.py
Labels: size:XS
