Repository explodinggradients/ragas, pull requests merged in 2024-12, with the labels that each got.

#1722 feat: add output type to metrics
  src/ragas/metrics/__init__.py
  src/ragas/metrics/_answer_correctness.py
  src/ragas/metrics/_answer_relevance.py
  src/ragas/metrics/_answer_similarity.py
  src/ragas/metrics/_aspect_critic.py
  src/ragas/metrics/_context_entities_recall.py
  src/ragas/metrics/_context_precision.py
  src/ragas/metrics/_context_recall.py
  src/ragas/metrics/_domain_specific_rubrics.py
  src/ragas/metrics/_factual_correctness.py
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/_goal_accuracy.py
  src/ragas/metrics/_instance_specific_rubrics.py
  src/ragas/metrics/_multi_modal_faithfulness.py
  src/ragas/metrics/_multi_modal_relevance.py
  src/ragas/metrics/_noise_sensitivity.py
  src/ragas/metrics/_simple_criteria.py
  src/ragas/metrics/_sql_semantic_equivalence.py
  src/ragas/metrics/_summarization.py
  src/ragas/metrics/_topic_adherence.py
  src/ragas/metrics/base.py
Labels: size:L

#1723 feat: dataloader for annotated json
  src/ragas/dataset_schema.py
  tests/unit/test_dataset_schema.py
Labels: size:L

#1701 feat: train your own evaluators
  src/ragas/config.py
  src/ragas/dataset_schema.py
  src/ragas/embeddings/base.py
  src/ragas/losses.py
  src/ragas/metrics/base.py
  src/ragas/optimizers/__init__.py
  src/ragas/optimizers/base.py
Labels: size:L

#1721 fix: attempting a simple fix for #1718
  src/ragas/executor.py
Labels: size:XS

#1733 fix: add missing query qualifier
  src/ragas/testset/synthesizers/multi_hop/abstract.py
  src/ragas/testset/synthesizers/multi_hop/specific.py
Labels: size:S

#1738 fix: Update README.md
  README.md
Labels: size:XS

#1724 feat: genetic algo based optimizer
  src/ragas/callbacks.py
  src/ragas/config.py
  src/ragas/dataset_schema.py
  src/ragas/evaluation.py
  src/ragas/executor.py
  src/ragas/losses.py
  src/ragas/metrics/base.py
  src/ragas/optimizers/__init__.py
  src/ragas/optimizers/base.py
  src/ragas/optimizers/genetic.py
  src/ragas/optimizers/utils.py
Labels: size:XL

#1727 Added native support for Gemini models generation completion signals in LangchainLLMWrapper class / is_finished method
  src/ragas/llms/base.py
Labels: size:S

#1728 Added custom is_finished_parser logic to Google Vertex AI customizati…
  docs/howtos/customizations/customize_models.md
Labels: size:M

#1741 feat: added basics for upload
  .gitignore
  pyproject.toml
  src/ragas/dataset_schema.py
  src/ragas/exceptions.py
  src/ragas/executor.py
  src/ragas/sdk.py
  src/ragas/testset/synthesizers/testset_schema.py
  src/ragas/utils.py
Labels: size:L

#1742 fix: correct url for upload()
  src/ragas/dataset_schema.py
  src/ragas/testset/synthesizers/testset_schema.py
Labels: size:XS

#1743 fix: prompt naming related issues
  src/ragas/callbacks.py
  src/ragas/optimizers/genetic.py
  src/ragas/prompt/mixin.py
Labels: size:S

#1747 feat: load from annotated testset
  src/ragas/testset/synthesizers/testset_schema.py
Labels: size:S

#1746 docs: add demo example for metric training
  docs/_static/edited_chain_runs.json
  docs/_static/imgs/after_training.png
  docs/_static/imgs/annotation.png
  docs/_static/imgs/before_training.png
  docs/howtos/customizations/index.md
  docs/howtos/customizations/metrics/_train_your_own_metric.md
  docs/howtos/customizations/metrics/train_your_own_metric.ipynb
  mkdocs.yml
Labels: size:XXL

#1750 docs: demo related fixes
  docs/_static/edited_chain_runs.json
  docs/howtos/customizations/index.md
  docs/howtos/customizations/metrics/train_your_own_metric.ipynb
  docs/howtos/customizations/metrics/train_your_own_metric.md
  mkdocs.yml
  src/ragas/optimizers/genetic.py
Labels: size:L

#1744 feat: replaced NLTK's implementation of BLEU with sacrebleu's implementation
  docs/concepts/metrics/available_metrics/traditional.md
  requirements/dev.txt
  src/ragas/metrics/_bleu_score.py
Labels: size:S

#1753 doc: add note
  docs/howtos/customizations/metrics/train_your_own_metric.md
Labels: size:XS

#1755 docs: add blog to readme
  README.md
Labels: size:XS

#1756 fixes: some minor fixes
  docs/howtos/customizations/_run_config.md
  src/ragas/callbacks.py
Labels: size:XS

#1754 docs: added ragas-app to getting started
  docs/getstarted/rag_evaluation.md
  docs/getstarted/rag_testset_generation.md
  docs/getstarted/ragas_evaluation_output_dashboard.png
  docs/getstarted/testset_output_dashboard.png
  docs/howtos/integrations/index.md
Labels: size:M

#1717 feat: add exact match caching
  .gitignore
  pyproject.toml
  requirements/test.txt
  src/ragas/__init__.py
  src/ragas/cache.py
  src/ragas/embeddings/base.py
  src/ragas/llms/base.py
  src/ragas/prompt/pydantic_prompt.py
  tests/unit/test_cache.py
Labels: size:L

#1759 fix: temperature needs to be added handled effectively
  src/ragas/llms/base.py
  src/ragas/optimizers/genetic.py
  tests/e2e/test_langchain_llm_attributes.py
Labels: size:M

#1765 Fix/hhem: divide by zero error
  src/ragas/metrics/_faithfulness.py
Labels: size:S

#1758 fix: add reference to simple scoring
  docs/howtos/applications/_metrics_llm_calls.md
  src/ragas/metrics/_simple_criteria.py
Labels: size:S

#1776 fix: import train config and add tests
  src/ragas/cache.py
  tests/conftest.py
  tests/unit/test_optimizer_config.py
Labels: size:M

#1777 chore: make analytics into threading
  DEVELOPMENT.md
  src/ragas/_analytics.py
  src/ragas/evaluation.py
  src/ragas/metrics/_bleu_score.py
  tests/unit/test_analytics.py
Labels: size:M

#1780 fix: change to schema
  src/ragas/dataset_schema.py
  src/ragas/metrics/base.py
  src/ragas/optimizers/genetic.py
Labels: size:S

#1762 Fix link to langchain and add pip install
  docs/getstarted/rag_testset_generation.md
Labels: size:XS

#1787 fix: distance measure in non llm CR
  src/ragas/metrics/_context_recall.py
Labels: size:S

#1790 fix: remove reproducibility arg
  src/ragas/evaluation.py
  src/ragas/integrations/llama_index.py
  src/ragas/metrics/_context_precision.py
  src/ragas/metrics/_context_recall.py
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/_noise_sensitivity.py
  src/ragas/metrics/base.py
Labels: size:M

#1794 Update README.md
  README.md
Labels: size:XS

#1801 docs: fix typo
  docs/getstarted/evals.md
Labels: size:XS
