Repository explodinggradients/ragas, pull requests merged in 2024-11, with the labels that each got.

#1609 feat: add support for llamaindex
  docs/howtos/integrations/_llamaindex.md
  docs/howtos/integrations/llamaindex.ipynb
  mkdocs.yml
  src/ragas/dataset_schema.py
  src/ragas/evaluation.py
  src/ragas/integrations/llama_index.py
  src/ragas/llms/base.py
  src/ragas/metrics/_factual_correctness.py
  src/ragas/metrics/_tool_call_accuracy.py
  src/ragas/testset/synthesizers/generate.py
Labels: size:XXL

#1606 docs: Add embedding_model attribute when creating TestsetGenerator object
  docs/getstarted/rag_testset_generation.md
Labels: size:XS

#1607 Fix: Add instance check before casting ChatGeneration object
  src/ragas/llms/base.py
Labels: size:XS

#1611 docs: add comment for claude-3-5-sonnet-20241022
  docs/extra/components/choose_evaluator_llm.md
  docs/extra/components/choose_generator_llm.md
  docs/howtos/customizations/customize_models.md
Labels: size:XS

#1612 docs: add community docs
  docs/community/index.md
Labels: size:S

#994 Handle embeddings for empty strings in AnswerSimilarity class
  src/ragas/metrics/_answer_similarity.py
Labels: size:XS

#1589 Feature: batched execution
  docs/howtos/integrations/llamaindex.ipynb
  src/ragas/async_utils.py
  src/ragas/dataset_schema.py
  src/ragas/evaluation.py
  src/ragas/executor.py
  src/ragas/integrations/llama_index.py
  src/ragas/llms/base.py
  src/ragas/testset/synthesizers/generate.py
  src/ragas/testset/transforms/engine.py
  src/ragas/utils.py
  src/ragas/validation.py
  tests/unit/test_async_utils.py
  tests/unit/test_executor.py
  tests/unit/test_executor_in_jupyter.ipynb
  tests/unit/test_utils.py
Labels: size:XL

#1610 docs: added azure openai to default docs
  docs/extra/components/choose_evaluator_llm.md
  docs/extra/components/choose_generator_llm.md
Labels: size:L

#1622 Introduce epsilon in denominators to avoid division by zero
  src/ragas/metrics/_topic_adherence.py
Labels: size:M

#1619 feat: Add support for llamaIndex in evaluation
  pyproject.toml
  src/ragas/evaluation.py
Labels: size:S

#1625 feat: added upload for `EvaluationResult`
  docs/howtos/customizations/metrics/write_your_own_metric.ipynb
  src/ragas/callbacks.py
  src/ragas/dataset_schema.py
  src/ragas/evaluation.py
  src/ragas/metrics/_context_entities_recall.py
  src/ragas/metrics/_context_precision.py
  src/ragas/metrics/_context_recall.py
  src/ragas/metrics/_summarization.py
  src/ragas/metrics/_topic_adherence.py
  src/ragas/utils.py
Labels: size:L

#1634 docs: Refactor Code for Syntax Highlighting and URL Updates
  docs/extra/components/choose_evaluator_llm.md
  docs/howtos/integrations/_llamaindex.md
  docs/howtos/integrations/llamaindex.ipynb
Labels: size:S

#1627 fix: remove `.` as a split condition in noise_sensitivity.py
  src/ragas/metrics/_noise_sensitivity.py
Labels: size:XS

#1621 feat: improvements in test synthesization
  docs/getstarted/rag_testset_generation.md
  docs/references/testset_schema.md
  src/ragas/metrics/_string.py
  src/ragas/testset/graph.py
  src/ragas/testset/graph_queries.py
  src/ragas/testset/synthesizers/__init__.py
  src/ragas/testset/synthesizers/abstract_query.py
  src/ragas/testset/synthesizers/base.py
  src/ragas/testset/synthesizers/base_query.py
  src/ragas/testset/synthesizers/generate.py
  src/ragas/testset/synthesizers/multi_hop/__init__.py
  src/ragas/testset/synthesizers/multi_hop/abstract.py
  src/ragas/testset/synthesizers/multi_hop/base.py
  src/ragas/testset/synthesizers/multi_hop/prompts.py
  src/ragas/testset/synthesizers/multi_hop/specific.py
  src/ragas/testset/synthesizers/prompts.py
  src/ragas/testset/synthesizers/single_hop/__init__.py
  src/ragas/testset/synthesizers/single_hop/base.py
  src/ragas/testset/synthesizers/single_hop/prompts.py
  src/ragas/testset/synthesizers/single_hop/specific.py
  src/ragas/testset/synthesizers/specific_query.py
  src/ragas/testset/transforms/base.py
  src/ragas/testset/transforms/default.py
  src/ragas/testset/transforms/extractors/llm_based.py
  src/ragas/testset/transforms/relationship_builders/__init__.py
  src/ragas/testset/transforms/relationship_builders/cosine.py
  src/ragas/testset/transforms/relationship_builders/traditional.py
  src/ragas/testset/transforms/splitters/headline.py
  src/ragas/utils.py
  tests/unit/prompt/test_prompt_mixin.py
  tests/unit/test_analytics.py
  tests/unit/test_prompt.py
Labels: size:XXL

#1629 feat: Unify the use of sentence_segmenter
  src/ragas/metrics/_bleu_score.py
  src/ragas/metrics/_factual_correctness.py
Labels: size:M

#1638 feat: aspect critic with reference
  docs/concepts/metrics/available_metrics/general_purpose.md
  src/ragas/metrics/_aspect_critic.py
Labels: size:L

#1639 docs: change setting llm
  docs/concepts/metrics/available_metrics/general_purpose.md
  docs/concepts/metrics/available_metrics/index.md
Labels: size:M

#1641 fixed wrong variable names in starter guide using azure openai
  docs/extra/components/choose_evaluator_llm.md
Labels: size:S

#1645 feat: improvements in test gen
  src/ragas/testset/graph.py
  src/ragas/testset/graph_queries.py
  src/ragas/testset/transforms/__init__.py
  src/ragas/testset/transforms/base.py
  src/ragas/testset/transforms/default.py
  src/ragas/testset/transforms/extractors/llm_based.py
  src/ragas/testset/transforms/filters.py
  src/ragas/testset/transforms/splitters/headline.py
Labels: size:L

#1636 Add tutorial for evaluating LangGraph agents
  docs/_static/imgs/_langgraph_agent_evaluation_28_0.jpg
  docs/howtos/integrations/_langgraph_agent_evaluation.md
  docs/howtos/integrations/langgraph_agent_evaluation.ipynb
  docs/references/integrations.md
  mkdocs.yml
  src/ragas/evaluation.py
  src/ragas/integrations/langgraph.py
  src/ragas/metrics/_topic_adherence.py
  tests/unit/test_langgraph.py
Labels: size:XXL

#1653 docs: add cost tracker back
  docs/howtos/customizations/metrics/_cost.md
  docs/howtos/customizations/metrics/cost.ipynb
Labels: size:L

#1652 docs: tracing and debugging metrics
  docs/howtos/customizations/index.md
  docs/howtos/customizations/metrics/_metrics_llm_calls.md
  docs/howtos/customizations/metrics/metrics_llm_calls.ipynb
  src/ragas/metrics/__init__.py
Labels: size:L

#1647 feat: upload testset generation upload
  docs/getstarted/rag_evaluation.md
  src/ragas/evaluation.py
  src/ragas/metrics/__init__.py
  src/ragas/testset/synthesizers/generate.py
  src/ragas/testset/synthesizers/single_hop/specific.py
  src/ragas/testset/synthesizers/testset_schema.py
  src/ragas/testset/transforms/extractors/llm_based.py
Labels: size:M

#1662 docs: reorganise files
  docs/howtos/applications/_metrics_llm_calls.md
  docs/howtos/applications/index.md
  docs/howtos/applications/metrics_llm_calls.ipynb
  docs/howtos/customizations/index.md
  mkdocs.yml
Labels: size:S

#1643 docs: fix _arize.md
  docs/howtos/integrations/_arize.md
  mkdocs.yml
Labels: size:S

#1664 docs: persona generator
  docs/howtos/customizations/metrics/_write_your_own_metric.md
  docs/howtos/customizations/testgenerator/_persona_generator.md
  docs/howtos/customizations/testgenerator/persona_generator.ipynb
  docs/howtos/integrations/_langgraph_agent_evaluation.md
  docs/howtos/integrations/_langgraph_agent_evaluation_files/_langgraph_agent_evaluation_23_0.jpg
  docs/howtos/integrations/_llamaindex.md
  mkdocs.yml
  src/ragas/testset/synthesizers/__init__.py
  src/ragas/testset/synthesizers/multi_hop/abstract.py
Labels: size:L

#1650 Bug fixing recall in _factual_correctness.py
  src/ragas/metrics/_factual_correctness.py
Labels: size:XS

#1669 Avoid unnecessary decompose_claims call when mode='precision' in _factual_correctness.py
  src/ragas/metrics/_factual_correctness.py
Labels: size:XS

#1672 fixes: instruction format
  src/ragas/prompt/pydantic_prompt.py
Labels: size:S

#1674 docs: updated readme
  README.md
Labels: size:XS

#1675 docs: update readme
  README.md
Labels: size:XS

#1673 fixes: add extraction limit to Extractors
  src/ragas/testset/transforms/extractors/llm_based.py
Labels: size:M

#1678 removed MetricWithLLM from SemanticSimilarity
  src/ragas/metrics/_answer_correctness.py
  src/ragas/metrics/_answer_similarity.py
Labels: size:XS

#1661 feat: improvements in default test generation
  src/ragas/testset/persona.py
  src/ragas/testset/synthesizers/__init__.py
  src/ragas/testset/synthesizers/generate.py
  src/ragas/testset/synthesizers/multi_hop/abstract.py
  src/ragas/testset/synthesizers/multi_hop/base.py
  src/ragas/testset/synthesizers/multi_hop/specific.py
  src/ragas/testset/synthesizers/single_hop/specific.py
  src/ragas/testset/transforms/default.py
  src/ragas/testset/transforms/extractors/llm_based.py
  src/ragas/testset/transforms/filters.py
  tests/unit/test_analytics.py
Labels: size:L

#1686 Update rag.md
  docs/concepts/test_data_generation/rag.md
Labels: size:XS

#1690 fix: missing embeddings argument in testset and some E2E tests
  src/ragas/metrics/_bleu_score.py
  src/ragas/testset/synthesizers/generate.py
  tests/benchmarks/benchmark_testsetgen.py
  tests/e2e/test_adaptation.py
  tests/e2e/test_amnesty_in_ci.py
  tests/e2e/test_evaluation_in_jupyter.ipynb
  tests/e2e/test_fullflow.py
  tests/e2e/test_langsmith.py
  tests/e2e/test_testset_gen_in_jupyter.ipynb
  tests/e2e/test_testset_generation.py
Labels: size:XL

#1680 fixes: handle long context extraction
  docs/extra/components/choose_generator_llm.md
  src/ragas/testset/transforms/base.py
  src/ragas/testset/transforms/extractors/llm_based.py
Labels: size:M

#1666 feat: make general purpose metrics more general
  docs/concepts/metrics/available_metrics/general_purpose.md
  docs/howtos/customizations/metrics/_cost.md
  docs/howtos/customizations/metrics/_write_your_own_metric.md
  docs/howtos/customizations/metrics/cost.ipynb
  docs/howtos/customizations/metrics/write_your_own_metric.ipynb
  docs/howtos/customizations/testgenerator/_persona_generator.md
  docs/howtos/customizations/testgenerator/persona_generator.ipynb
  docs/howtos/integrations/_langgraph_agent_evaluation.md
  docs/howtos/integrations/langchain.ipynb
  docs/howtos/integrations/langgraph_agent_evaluation.ipynb
  src/ragas/dataset_schema.py
  src/ragas/embeddings/base.py
  src/ragas/llms/base.py
  src/ragas/metrics/__init__.py
  src/ragas/metrics/_answer_similarity.py
  src/ragas/metrics/_aspect_critic.py
  src/ragas/metrics/_domain_specific_rubrics.py
  src/ragas/metrics/_instance_specific_rubrics.py
  src/ragas/metrics/_noise_sensitivity.py
  src/ragas/metrics/_simple_criteria.py
  src/ragas/metrics/base.py
  src/ragas/prompt/pydantic_prompt.py
  src/ragas/testset/transforms/__init__.py
  src/ragas/testset/transforms/default.py
  src/ragas/testset/transforms/extractors/llm_based.py
  src/ragas/utils.py
  src/ragas/validation.py
Labels: size:XXL

#1685 Fixes ToolCallAccuracy raises ZeroDivisionError when called without any arguments.
  src/ragas/metrics/_tool_call_accuracy.py
Labels: size:XS

#1698 feat: test-generation improvements
  docs/howtos/customizations/index.md
  docs/howtos/customizations/testgenerator/_testgen-custom-single-hop.md
  docs/howtos/customizations/testgenerator/_testgen-customisation.md
  docs/howtos/customizations/testgenerator/testgen-custom-single-hop.ipynb
  docs/howtos/customizations/testgenerator/testgen-customisation.ipynb
  mkdocs.yml
  src/ragas/testset/graph.py
  src/ragas/testset/synthesizers/multi_hop/abstract.py
  src/ragas/testset/synthesizers/multi_hop/base.py
  src/ragas/testset/synthesizers/multi_hop/prompts.py
  src/ragas/testset/synthesizers/multi_hop/specific.py
  src/ragas/testset/synthesizers/single_hop/base.py
  src/ragas/testset/synthesizers/single_hop/prompts.py
  src/ragas/testset/synthesizers/single_hop/specific.py
  src/ragas/testset/transforms/__init__.py
  src/ragas/testset/transforms/relationship_builders/traditional.py
  src/ragas/testset/transforms/splitters/headline.py
Labels: size:XXL

#1716 chore: updated tracking for single scores
  src/ragas/_analytics.py
  src/ragas/evaluation.py
  src/ragas/metrics/base.py
  src/ragas/utils.py
  tests/unit/test_analytics.py
Labels: size:L

#1708 feat: remove examples
  src/ragas/metrics/_aspect_critic.py
  src/ragas/metrics/_simple_criteria.py
  src/ragas/testset/synthesizers/testset_schema.py
  tests/unit/test_metric.py
Labels: size:M

#1714 Bug in documentation rag_testset_generation.md: API changes required arguments
  docs/getstarted/rag_testset_generation.md
Labels: size:XS
