Repository explodinggradients/ragas, pull requests merged in 2024-08, with the labels that each got.

#1142 Random seed fixed.
  src/ragas/run_config.py
  src/ragas/testset/docstore.py
  src/ragas/testset/evolutions.py
Labels: size:S

#1129 feat: Usage tracking for evaluations
  docs/howtos/applications/cost.ipynb
  docs/howtos/applications/index.md
  src/experimental/ragas_experimental/testset/extractors/regex_based.py
  src/experimental/ragas_experimental/testset/loaders/__init__.py
  src/experimental/ragas_experimental/testset/loaders/ragas_loader.py
  src/experimental/ragas_experimental/testset/loaders/test_async.py
  src/experimental/ragas_experimental/testset/loaders/test_sync.py
  src/ragas/cost.py
  src/ragas/evaluation.py
  src/ragas/integrations/llama_index.py
  src/ragas/llms/base.py
  src/ragas/run_config.py
  src/ragas/testset/docstore.py
  src/ragas/testset/evolutions.py
  src/ragas/testset/generator.py
  src/ragas/utils.py
  tests/unit/test_cost.py
  tests/unit/test_utils.py
Labels: size:XL

#1153 Fixing Demo Code - Compare Embeddings for retriever Docs
  docs/howtos/applications/compare_embeddings.md
Labels: size:XS

#1158 fix: run_config post_init issue
  src/ragas/run_config.py
  tests/unit/test_run_config.py
Labels: size:S

#1157 Add save function for statement_prompt
  src/ragas/metrics/_faithfulness.py
Labels: size:XS

#1159 fix: `RunConfig` documentation and improvements
  docs/getstarted/evaluation.md
  docs/getstarted/testset_generation.md
  docs/howtos/customisations/index.md
  docs/howtos/customisations/ragas_custom_model.ipynb
  docs/howtos/customisations/run_config.ipynb
  docs/references/index.rst
  docs/references/run_config.rst
  src/ragas/evaluation.py
  src/ragas/executor.py
  src/ragas/integrations/llama_index.py
  src/ragas/metrics/base.py
  src/ragas/run_config.py
  src/ragas/utils.py
Labels: size:L

#1160 Docs/run config
  docs/getstarted/evaluation.md
  docs/getstarted/testset_generation.md
Labels: size:XS

#1166 change default model to gpt4o-mini
  src/ragas/llms/base.py
  src/ragas/testset/generator.py
Labels: size:XS

#1169 Add tests to `ragas.run_config.RunConfig` `rng` attribute.
  tests/unit/test_run_config.py
Labels: size:M

#1171 feat: added `track_completed` decorator to track completed functions
  src/ragas/_analytics.py
  src/ragas/evaluation.py
  src/ragas/testset/generator.py
  tests/unit/test_analytics.py
Labels: size:M

#1115 docs: added development.md file
  DEVELOPMENT.md
Labels: size:M

#1161 Allow Metric.score to work within an existing asyncio loop
  .github/workflows/ci.yaml
  src/ragas/metrics/base.py
  tests/e2e/test_evaluation_in_jupyter.ipynb
  tests/unit/test_executor_in_jupyter.ipynb
  tests/unit/test_metric.py
Labels: size:M

#1173 Add question to context recall doc
  docs/concepts/metrics/context_recall.md
Labels: size:XS

#1174 Add context utilization
  docs/concepts/metrics/context_recall.md
  docs/concepts/metrics/context_utilization.md
  docs/concepts/metrics/index.md
  src/ragas/metrics/_context_precision.py
Labels: size:M

#1178 Helicone Integration
  docs/howtos/integrations/helicone.ipynb
Labels: size:L

#1183 docs: minor fixes
  docs/concepts/metrics/context_recall.md
  docs/howtos/integrations/helicone.ipynb
  docs/howtos/integrations/index.md
Labels: size:XS

#1181 solved issue that adaptation crashes when havig multiple nested promp…
  src/ragas/llms/prompt.py
Labels: size:XS

#1164 Bugfix Summarization Score
  docs/howtos/customisations/run_config.ipynb
  src/ragas/metrics/_summarization.py
  src/ragas/metrics/base.py
  src/ragas/testset/prompts.py
  tests/unit/test_analytics.py
  tests/unit/test_executor_in_jupyter.ipynb
  tests/unit/test_run_config.py
Labels: size:L

#1184 [DOCS] - Fix summarization score expression
  docs/concepts/metrics/summarization_score.md
Labels: size:XS

#1195 Fix test command in development.md to match Makefile configuration
  DEVELOPMENT.md
Labels: size:XS

#1197 fix: added a test for prompts
  src/ragas/llms/prompt.py
  tests/unit/llms/test_prompt.py
Labels: size:S

#1198 fix: typo in model name
  docs/concepts/metrics/faithfulness.md
Labels: size:XS

#1189 metrics: add domain specific rubrics based scoring
  src/ragas/metrics/__init__.py
  src/ragas/metrics/_rubrics_based.py
Labels: size:L

#1200 docs: rubrics based metrics
  docs/concepts/metrics/index.md
  docs/concepts/metrics/rubrics_based.md
Labels: size:M

#1202 docs: add context utilisation to the index
  docs/concepts/metrics/index.md
Labels: size:XS

#1219 Tiny typo fix: it's -> its
  docs/concepts/index.md
Labels: size:XS

#1216 fix : solves #1215 - Inconsistency in the Value of EVALMODE_TO_COLUMNS[EvaluationMode.ca]
  src/ragas/validation.py
Labels: size:XS

#1225 chore: removed extra of requirements
  .gitignore
  pyproject.toml
  src/ragas/integrations/langchain.py
Labels: size:XS

#1223 Bugfix of evaluate function in llama_index.py
  src/ragas/integrations/llama_index.py
Labels: size:XS

#1201 [FIX] - Fix for summarization edge case
  docs/concepts/metrics/summarization_score.md
  src/ragas/metrics/_summarization.py
Labels: size:M
