Repository explodinggradients/ragas, pull requests merged in 2024-02, with the labels that each got.

#628 Made embeddings and LLMs dependent on metric in evaluate function
  src/ragas/evaluation.py
Labels: enhancement, bug_fix

#638 Fix typo: Teset -> Testset
  src/ragas/_analytics.py
  src/ragas/testset/generator.py
  tests/unit/test_analytics.py
Labels: bug_fix

#640 renaming ground_truths to ground_truth.
  README.md
  docs/concepts/metrics/answer_correctness.md
  docs/concepts/metrics/context_recall.md
  docs/concepts/metrics/semantic_similarity.md
  docs/howtos/applications/compare_llms.md
  docs/howtos/applications/custom_prompts.md
  docs/howtos/applications/data_preparation.md
  docs/howtos/applications/use_prompt_adaptation.md
  docs/howtos/customisations/aws-bedrock.ipynb
  docs/howtos/customisations/azure-openai.ipynb
  docs/howtos/customisations/gcp-vertexai.ipynb
  docs/howtos/integrations/langchain.ipynb
  docs/howtos/integrations/langfuse.ipynb
  docs/howtos/integrations/llamaindex.ipynb
  docs/howtos/integrations/zeno.ipynb
  src/ragas/evaluation.py
  src/ragas/exceptions.py
  src/ragas/metrics/base.py
Labels: enhancement
