Repository explodinggradients/ragas, pull requests merged in 2024-07, with the labels that each got.

#1026 Docs for summarization metric
  docs/concepts/metrics/index.md
  docs/concepts/metrics/summarization_score.md
  docs/references/metrics.rst
Labels: size:M

#1025 adding `get_available_metrics` method
  src/ragas/metrics/utils.py
  tests/unit/test_metric.py
Labels: size:M

#1058 chore: Fix typo in index.md
  docs/index.md
Labels: size:XS

#1001 fix(testset): for generating testset with new docs
  src/ragas/testset/evolutions.py
  src/ragas/testset/generator.py
Labels: size:S

#995 Fix counter in Runner and Executor in case of any exception
  src/ragas/executor.py
Labels: size:S

#979 Chore: Fix RuntimeError: ... got Future <..> attached to a different loop
  src/ragas/executor.py
Labels: size:XS

#1051 fix: langchain EvaluatorChain OpenAI validation error
  src/ragas/integrations/langchain.py
  src/ragas/utils.py
Labels: size:S

#1061 chore: removed async time tests from benchmarks
  src/ragas/metrics/base.py
  src/ragas/testset/generator.py
  src/ragas/utils.py
  tests/benchmarks/benchmark_eval.py
  tests/benchmarks/benchmark_testsetgen.py
  tests/unit/test_metric.py
Labels: size:M

#1081 chore: added analytics to count the num of testsets generated with experimental
  src/experimental/ragas_experimental/testset/generators/simple.py
  src/ragas/_analytics.py
  src/ragas/testset/generator.py
Labels: size:S

#1082 Fix mutable dataclass defaults
  src/experimental/ragas_experimental/testset/generators/base.py
Labels: size:XS

#1093 fix(executor): simplify executor by removing threading
  Makefile
  requirements/test.txt
  src/ragas/executor.py
  tests/unit/test_executor.py
  tests/unit/test_executor_in_jupyter.ipynb
Labels: size:L

#1095 chore: added ragas as a dependency
  src/experimental/pyproject.toml
Labels: size:XS

#1110 test: added more tests for executor
  Makefile
  tests/e2e/test_evaluation_in_jupyter.ipynb
  tests/e2e/test_testset_gen_in_jupyter.ipynb
  tests/unit/test_executor_in_jupyter.ipynb
Labels: size:L

#1111 chore: remove context_relevancy from library
  docs/concepts/metrics/context_relevancy.md
  docs/concepts/metrics/index.md
  src/ragas/metrics/__init__.py
  src/ragas/metrics/_context_relevancy.py
  src/ragas/metrics/utils.py
  tests/unit/test_import.py
Labels: size:L

#1117 Update index.md
  docs/community/index.md
Labels: size:XS

#1114 Improve Clarity and Structure of Faithfulness Explanation in Documentation
  docs/concepts/metrics/faithfulness.md
Labels: size:XS

#1116 fix: remove `is_async` argument since everything is async now
  src/experimental/ragas_experimental/testset/__init__.py
  src/experimental/ragas_experimental/testset/extractors/base.py
  src/experimental/ragas_experimental/testset/extractors/llm_based.py
  src/experimental/ragas_experimental/testset/extractors/regex_based.py
  src/experimental/ragas_experimental/testset/generators/base.py
  src/experimental/ragas_experimental/testset/generators/simple.py
  src/experimental/ragas_experimental/testset/relationships/relation.py
  src/experimental/ragas_experimental/testset/relationships/similarity.py
  src/experimental/ragas_experimental/testset/utils.py
  src/ragas/callbacks.py
  src/ragas/evaluation.py
  src/ragas/llms/prompt.py
  src/ragas/metrics/_answer_correctness.py
  src/ragas/metrics/_answer_relevance.py
  src/ragas/metrics/_answer_similarity.py
  src/ragas/metrics/_context_entities_recall.py
  src/ragas/metrics/_context_precision.py
  src/ragas/metrics/_context_recall.py
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/_summarization.py
  src/ragas/metrics/base.py
  src/ragas/metrics/critique.py
  src/ragas/testset/prompts.py
  tests/e2e/test_evaluation_in_jupyter.ipynb
  tests/e2e/test_testset_gen_in_jupyter.ipynb
  tests/unit/test_executor.py
  tests/unit/test_executor_in_jupyter.ipynb
Labels: size:L

#1071 [Fix bug] The adaptation for `rewrite_invalid_question_prompt` was not saved
  src/ragas/testset/evolutions.py
Labels: size:XS

#1083 [Fix bug] utils.py
  src/ragas/utils.py
Labels: size:XS

#1085 Llama Index integration: optional RunConfig for evaluate()
  src/ragas/integrations/llama_index.py
Labels: size:XS

#1122 Create a custom directory loader for RAGAS
  src/experimental/ragas_experimental/testset/loaders/__init__.py
  src/experimental/ragas_experimental/testset/loaders/ragas_loader.py
  src/experimental/ragas_experimental/testset/loaders/test_async.py
  src/experimental/ragas_experimental/testset/loaders/test_sync.py
Labels: size:L

#1126 Fix "sentence" -> "claim" the context recall metric docs
  docs/concepts/metrics/context_recall.md
Labels: size:XS

#887 fix: temperature parameter in generate_text not ignored.
  src/ragas/llms/base.py
Labels: size:S

#1113 Fix "global flags not at the start" raised in extract_text function
  src/experimental/ragas_experimental/testset/extractors/regex_based.py
Labels: size:M
