Repository explodinggradients/ragas, pull requests merged in 2024-10, with the labels that each got.

#1386 feat: output new Testset object for generation
  src/ragas/dataset_schema.py
  src/ragas/experimental/testset/simulators/__init__.py
  src/ragas/experimental/testset/simulators/abstract_qa.py
  src/ragas/experimental/testset/simulators/base.py
  src/ragas/experimental/testset/simulators/generate.py
  src/ragas/experimental/testset/simulators/testset_schema.py
  src/ragas/metrics/_answer_relevance.py
Labels: size:L

#1390 Update answer_relevance.md: Minor spell correct
  docs/concepts/metrics/answer_relevance.md
Labels: size:XS

#1392 feat: support for callbacks and traces in testset generation
  docs/getstarted/rag_testset_generation.ipynb
  src/ragas/experimental/testset/simulators/abstract_qa.py
  src/ragas/experimental/testset/simulators/base.py
  src/ragas/experimental/testset/simulators/base_qa.py
  src/ragas/experimental/testset/simulators/generate.py
  src/ragas/experimental/testset/simulators/specific_qa.py
  src/ragas/testset/evolutions.py
Labels: size:L

#1396 non-asii characters support in faithfulness
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/_noise_sensitivity.py
Labels: size:XS

#1391 feat: get and set prompts mixin
  src/ragas/experimental/prompt.py
  src/ragas/experimental/testset/simulators/base.py
  src/ragas/experimental/testset/transforms/base.py
  src/ragas/metrics/base.py
Labels: size:M

#1394 chore!: moving to pydantic2
  pyproject.toml
  src/ragas/_analytics.py
  src/ragas/cost.py
  src/ragas/llms/output_parser.py
  src/ragas/metrics/_answer_correctness.py
  src/ragas/metrics/_answer_relevance.py
  src/ragas/metrics/_context_entities_recall.py
  src/ragas/metrics/_context_precision.py
  src/ragas/metrics/_context_recall.py
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/_noise_sensitivity.py
  src/ragas/metrics/_summarization.py
  src/ragas/testset/prompts.py
  tests/unit/testset_generator/test_docstore.py
  tests/unit/testset_generator/test_document.py
  tests/unit/testset_generator/test_embs.pkl
Labels: size:L

#1398 docs: improve getting started
  docs/getstarted/index.md
  docs/getstarted/rag_testset_generation.ipynb
  docs/getstarted/rag_testset_generation.md
Labels: size:L

#1404 Fix typo in metric error message
  src/ragas/validation.py
Labels: size:XS

#1407 feat: renamed sample operations and cleaned up test warnings
  pyproject.toml
  src/ragas/dataset_schema.py
  src/ragas/experimental/metrics/_faithfulness.py
  src/ragas/integrations/langchain.py
  src/ragas/metrics/_answer_correctness.py
  src/ragas/metrics/_answer_relevance.py
  src/ragas/metrics/_answer_similarity.py
  src/ragas/metrics/_aspect_critic.py
  src/ragas/metrics/_context_entities_recall.py
  src/ragas/metrics/_context_precision.py
  src/ragas/metrics/_context_recall.py
  src/ragas/metrics/_domain_specific_rubrics.py
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/_instance_specific_rubrics.py
  src/ragas/metrics/_noise_sensitivity.py
  src/ragas/metrics/_simple_criteria.py
  src/ragas/metrics/_summarization.py
  src/ragas/metrics/base.py
  src/ragas/validation.py
  tests/unit/llms/test_prompt_old.py
  tests/unit/test_dataset_schema.py
  tests/unit/test_import.py
  tests/unit/test_metric.py
Labels: size:L

#1389 added better styling to reder jupyter notebooks nicely.
  docs/extra/style.css
Labels: size:M

#1402 docs: add core concepts for test generation
  docs/_static/imgs/scenario_rag.png
  docs/concepts/test_data_generation/rag.md
  mkdocs.yml
Labels: size:L

#1408 docs:Auto Gen of Reference Page
  Makefile
  docs/references/evaluation.md
  docs/references/index.md
  docs/references/metrics.md
  docs/references/run_config.md
  docs/references/testset_generation.md
  mkdocs.yml
  scripts/gen_ref_pages.py
Labels: size:L

#1410 fix key error for FaithfulnesswithHHEM
  src/ragas/metrics/_faithfulness.py
Labels: size:XS

#1409 fix: remove usage of contexts in response relevancy
  src/ragas/metrics/_answer_relevance.py
Labels: size:L

#1406 feat: NER extractor and Jaccard
  src/ragas/testset/transforms/extractors/__init__.py
  src/ragas/testset/transforms/extractors/llm_based.py
  src/ragas/testset/transforms/relationship_builders/cosine.py
  tests/unit/test_analytics.py
Labels: size:L

#1413 feat(styles): refactor CSS to use custom variables
  docs/extra/style.css
Labels: size:L

#1412 docs : add customisation
  docs/getstarted/rag_evaluation.md
  docs/howtos/customisations/aws-bedrock.ipynb
  docs/howtos/customisations/azure-openai.ipynb
  docs/howtos/customisations/bring-your-own-llm-or-embs.md
  docs/howtos/customisations/customise_models.md
  docs/howtos/customisations/gcp-vertexai.ipynb
  docs/howtos/customisations/index.md
  docs/howtos/customisations/metrics/Write_your_own_metric.ipynb
  docs/howtos/customisations/metrics/modifying-prompts-metrics.ipynb
  docs/howtos/customisations/ragas_custom_model.ipynb
  docs/howtos/customisations/run_config.ipynb
  docs/howtos/index.md
Labels: size:XXL

#1414 feat(docs): add support for reusable snippets
  docs/extra/components/choose_evaluvator_llm.md
  docs/getstarted/rag_evaluation.md
  docs/getstarted/rag_testset_generation.md
  mkdocs.yml
Labels: size:L

#1415 Feature/css variables
  docs/extra/style.css
  mkdocs.yml
Labels: size:M

#1416 docs: fix nav bar
  docs/concepts/feedback/index.md
  docs/concepts/metrics/available_metrics/agents.md
  docs/concepts/metrics/available_metrics/answer_correctness.md
  docs/concepts/metrics/available_metrics/answer_relevance.md
  docs/concepts/metrics/available_metrics/aspect_critic.md
  docs/concepts/metrics/available_metrics/context_entities_recall.md
  docs/concepts/metrics/available_metrics/context_precision.md
  docs/concepts/metrics/available_metrics/context_recall.md
  docs/concepts/metrics/available_metrics/factual_correctness.md
  docs/concepts/metrics/available_metrics/faithfulness.md
  docs/concepts/metrics/available_metrics/general_purpose.md
  docs/concepts/metrics/available_metrics/index.md
  docs/concepts/metrics/available_metrics/noise_sensitivity.md
  docs/concepts/metrics/available_metrics/rubrics_based.md
  docs/concepts/metrics/available_metrics/semantic_similarity.md
  docs/concepts/metrics/available_metrics/sql.md
  docs/concepts/metrics/available_metrics/summarization_score.md
  docs/concepts/metrics/available_metrics/topic_adherence.md
  docs/concepts/metrics/available_metrics/traditional.md
  docs/concepts/metrics/index.md
  docs/concepts/metrics/overview/index.md
  docs/concepts/test_data_generation/agents.md
  docs/howtos/customizations/customize_models.md
  docs/howtos/customizations/index.md
  docs/howtos/customizations/metrics/modifying-prompts-metrics.ipynb
  docs/howtos/customizations/metrics/write_your_own_metric.ipynb
  docs/howtos/customizations/run_config.ipynb
  docs/howtos/index.md
  mkdocs.yml
Labels: size:L

#1418 feat: more features to prompt object
  Makefile
  docs/howtos/customizations/metrics/modifying-prompts-metrics.ipynb
  docs/howtos/customizations/metrics/write_your_own_metric.ipynb
  docs/howtos/customizations/run_config.ipynb
  pyproject.toml
  src/ragas/exceptions.py
  src/ragas/integrations/langchain.py
  src/ragas/llms/base.py
  src/ragas/llms/output_parser.py
  src/ragas/metrics/_answer_correctness.py
  src/ragas/metrics/_answer_relevance.py
  src/ragas/metrics/_context_entities_recall.py
  src/ragas/metrics/_context_precision.py
  src/ragas/metrics/_context_recall.py
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/_summarization.py
  src/ragas/metrics/base.py
  src/ragas/prompt.py
  src/ragas/prompt/__init__.py
  src/ragas/prompt/base.py
  src/ragas/prompt/mixin.py
  src/ragas/testset/transforms/extractors/llm_based.py
  src/ragas/utils.py
  tests/unit/test_executor.py
  tests/unit/test_prompt.py
  tests/unit/test_utils.py
Labels: size:XL

#1419 chore: add tracking for new testset generation
  src/ragas/_analytics.py
  src/ragas/testset/synthesizers/generate.py
Labels: size:S

#1429 feat: adapt prompt to different languages
  src/ragas/prompt/__init__.py
  src/ragas/prompt/base.py
  src/ragas/prompt/mixin.py
  src/ragas/prompt/pydantic_prompt.py
  src/ragas/prompt/utils.py
  tests/unit/prompt/test_prompt_utils.py
Labels: size:XL

#1428 chores: add reference to gitignore
  .gitignore
Labels: size:XS

#1427 docs: redo intro
  docs/index.md
Labels: size:S

#1431 Add Custom Ragas Light and Dark Themes (v1)
  docs/_static/imgs/logo-black.svg
  docs/_static/js/header_border.js
  docs/extra/style.css
  mkdocs.yml
Labels: size:L

#1436 fix attribute error for faithfulness metric
  src/ragas/metrics/_faithfulness.py
Labels: size:XS

#1446 docs: language adaptation
  docs/howtos/customizations/index.md
  docs/howtos/customizations/metrics/metrics_language_adaptation.ipynb
Labels: size:L

#1460 fix: added an extra import
  tests/unit/test_import.py
Labels: size:XS

#1458 feat: save and load Prompts
  src/ragas/prompt/base.py
  src/ragas/prompt/mixin.py
  src/ragas/prompt/pydantic_prompt.py
  src/ragas/testset/synthesizers/abstract_query.py
  src/ragas/testset/synthesizers/prompts.py
  tests/conftest.py
  tests/unit/prompt/test_prompt_mixin.py
  tests/unit/test_prompt.py
Labels: size:L

#1462 refactor: convert faithfulness, answer_correctness and noise_sensitivity to new prompt object
  src/ragas/experimental/metrics/__init__.py
  src/ragas/experimental/metrics/_faithfulness.py
  src/ragas/metrics/_answer_correctness.py
  src/ragas/metrics/_factual_correctness.py
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/_noise_sensitivity.py
Labels: size:XXL

#1452 Minor typo in _answer_relevance.py
  src/ragas/metrics/_answer_relevance.py
Labels: size:XS

#1459 feat: added repr for prompt objects
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/_noise_sensitivity.py
  src/ragas/prompt/base.py
  src/ragas/prompt/pydantic_prompt.py
Labels: size:M

#1473 docs: fix invalid links and imports
  docs/concepts/components/eval_sample.md
  docs/concepts/components/prompt.md
  docs/concepts/index.md
  docs/concepts/metrics/available_metrics/agents.md
  docs/concepts/metrics/available_metrics/answer_relevance.md
  docs/concepts/metrics/available_metrics/context_entities_recall.md
  docs/concepts/metrics/available_metrics/context_precision.md
  docs/concepts/metrics/available_metrics/context_recall.md
  docs/concepts/metrics/available_metrics/factual_correctness.md
  docs/concepts/metrics/available_metrics/faithfulness.md
  docs/concepts/metrics/available_metrics/general_purpose.md
  docs/concepts/metrics/available_metrics/noise_sensitivity.md
  docs/concepts/metrics/available_metrics/semantic_similarity.md
  docs/concepts/metrics/available_metrics/sql.md
  docs/concepts/metrics/available_metrics/summarization_score.md
  docs/concepts/metrics/available_metrics/topic_adherence.md
  docs/concepts/metrics/available_metrics/traditional.md
  docs/concepts/metrics/overview/index.md
  docs/concepts/prompt_adaptation.md
  docs/concepts/prompts.md
  docs/concepts/test_data_generation/rag.md
  docs/concepts/testset_generation.md
  docs/getstarted/index.md
  docs/getstarted/install.md
  docs/getstarted/rag_evaluation.md
  docs/getstarted/rag_testset_generation.md
  docs/howtos/customizations/index.md
  docs/howtos/customizations/metrics/metrics_language_adaptation.ipynb
  docs/howtos/customizations/metrics/modifying-prompts-metrics.ipynb
  docs/howtos/customizations/metrics/write_your_own_metric.ipynb
  docs/howtos/customizations/testgenerator/index.md
  mkdocs.yml
  src/ragas/metrics/__init__.py
  src/ragas/metrics/_answer_similarity.py
Labels: size:XL

#1469 feat: changed summary to new prompt
  src/ragas/metrics/_summarization.py
Labels: size:L

#1480 docs: redo readme
  README.md
  docs/concepts/metrics/overview/index.md
Labels: size:M

#1474 docs: new build process with rtd and API documentation
  .gitignore
  .readthedocs.yml
  docs/references/embeddings.md
  docs/references/evaluate.md
  docs/references/evaluation_schema.md
  docs/references/executor.md
  docs/references/generate.md
  docs/references/graph.md
  docs/references/integrations.md
  docs/references/llms.md
  docs/references/metrics.md
  docs/references/prompt.md
  docs/references/run_config.md
  docs/references/synthesizers.md
  docs/references/testset_schema.md
  docs/references/transforms.md
  mkdocs.yml
  scripts/gen_ref_pages.py
  src/ragas/__init__.py
  src/ragas/adaptation.py
  src/ragas/dataset_schema.py
  src/ragas/embeddings/__init__.py
  src/ragas/embeddings/base.py
  src/ragas/executor.py
  src/ragas/llms/base.py
  src/ragas/messages.py
  src/ragas/metrics/base.py
  src/ragas/prompt/__init__.py
  src/ragas/prompt/mixin.py
  src/ragas/run_config.py
  src/ragas/testset/graph.py
  src/ragas/testset/synthesizers/__init__.py
  src/ragas/testset/synthesizers/abstract_query.py
  src/ragas/testset/synthesizers/base.py
  src/ragas/testset/synthesizers/base_query.py
  src/ragas/testset/synthesizers/generate.py
  src/ragas/testset/synthesizers/specific_query.py
  src/ragas/testset/synthesizers/testset_schema.py
  src/ragas/testset/transforms/__init__.py
  src/ragas/testset/transforms/engine.py
  src/ragas/testset/transforms/extractors/embeddings.py
  src/ragas/testset/transforms/extractors/llm_based.py
Labels: size:XL

#1481 chore: added install for mkdocs insiders
  .readthedocs.yml
  mkdocs.yml
Labels: size:S

#1483 chores: update gitignore
  .gitignore
  README.md
Labels: size:XS

#1489 docs: improve testgen namings
  docs/concepts/test_data_generation/rag.md
Labels: size:M

#1492 feat: added save and load to RagasDataset
  .gitignore
  .readthedocs.yml
  Makefile
  docs/getstarted/rag_evaluation.md
  docs/howtos/migrations/migrate_from_v01_to_v02.md
  mkdocs.yml
  scripts/gen_ref_pages.py
  src/ragas/dataset_schema.py
  src/ragas/llms/prompt.py
  src/ragas/metrics/_summarization.py
  src/ragas/testset/synthesizers/base.py
  src/ragas/testset/synthesizers/testset_schema.py
  tests/unit/test_dataset_schema.py
Labels: size:L

#1482 docs: moved from ipnb files to md files
  .readthedocs.yml
  Makefile
  docs/howtos/applications/_cost.md
  docs/howtos/applications/compare_embeddings.md
  docs/howtos/applications/compare_llms.md
  docs/howtos/customizations/_run_config.md
  docs/howtos/customizations/index.md
  docs/howtos/customizations/metrics/_metrics_language_adaptation.md
  docs/howtos/customizations/metrics/_modifying-prompts-metrics.md
  docs/howtos/customizations/metrics/_write_your_own_metric.md
  docs/howtos/integrations/_arize.md
  docs/howtos/integrations/_athina.md
  docs/howtos/integrations/_haystack.md
  docs/howtos/integrations/_helicone.md
  docs/howtos/integrations/_langchain.md
  docs/howtos/integrations/_langfuse.md
  docs/howtos/integrations/_langsmith.md
  docs/howtos/integrations/_llamaindex.md
  docs/howtos/integrations/_openlayer.md
  docs/howtos/integrations/_opik.md
  docs/howtos/integrations/_tonic-validate.md
  docs/howtos/integrations/_zeno.md
  mkdocs.yml
  scripts/ipynb_to_md.py
Labels: size:XXL

#1494 feat: set ensure_ascii to false
  src/ragas/dataset_schema.py
  src/ragas/metrics/base.py
  src/ragas/prompt/pydantic_prompt.py
Labels: size:S

#1498 Fix Discord link
  README.md
Labels: size:XS

#1499 Fix Quickstart link
  README.md
Labels: size:XS

#1500 Rewrite Open Analytics
  README.md
Labels: size:S

#1501 Suggestions for Introduction and Key Features
  README.md
Labels: size:S

#1502 docs: fix broken links in testset generation custimisation
  README.md
  docs/howtos/applications/_cost.md
  mkdocs.yml
Labels: size:M

#1487 Update Bedrock modules for LangChain v0.3.x
  docs/extra/components/choose_evaluvator_llm.md
  docs/howtos/customizations/customize_models.md
Labels: size:M

#1504 Fixes: Quickstart Ragas Metrics
  README.md
  docs/getstarted/rag_evaluation.md
Labels: size:M

#1505 Add Contributors
  README.md
Labels: size:S

#1507 docs: Change test_size parameter name to testset_size
  docs/getstarted/rag_testset_generation.md
Labels: size:XS

#1511 docs: readme add llm
  README.md
Labels: size:XS

#1503 docs: add faq
  docs/_static/js/toggle.js
  docs/extra/style.css
  docs/index.md
  mkdocs.yml
Labels: size:M

#1513 fix: propagate callbacks in RagasOutputParser
  src/ragas/prompt/pydantic_prompt.py
Labels: size:XS

#1514 docs: fix usage of eval dataset
  docs/concepts/components/eval_dataset.md
  docs/getstarted/rag_evaluation.md
Labels: size:M

#1518 feat: use ensure_ascii=False for KnowledgeGraph files
  src/ragas/testset/graph.py
Labels: size:XS

#1516 fix: import error for TestsetGeneration and small fixes
  src/ragas/dataset_schema.py
  src/ragas/testset/synthesizers/testset_schema.py
  tests/unit/test_dataset_schema.py
  tests/unit/test_testset_schema.py
Labels: size:L

#1510 docs: update summarization calculation
  docs/concepts/metrics/available_metrics/summarization_score.md
Labels: size:XS

#1520 fix: use get_temperature in base LLM generate
  src/ragas/llms/base.py
Labels: size:XS

#1525 doc: Update modifying prompts metrics doc
  docs/howtos/customizations/metrics/_modifying-prompts-metrics.md
  docs/howtos/customizations/metrics/modifying-prompts-metrics.ipynb
Labels: size:XS

#1523 fixbug: Expand sentence-ending punctuation check in _create_statements method
  src/ragas/metrics/_faithfulness.py
Labels: size:XS

#1530 fix: zero division error
  src/ragas/metrics/_factual_correctness.py
  src/ragas/testset/synthesizers/testset_schema.py
Labels: size:S

#1531 feat: add traces to `EvaluationResult`
  src/ragas/callbacks.py
  src/ragas/dataset_schema.py
  src/ragas/evaluation.py
  src/ragas/metrics/_aspect_critic.py
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/base.py
  src/ragas/prompt/pydantic_prompt.py
  tests/unit/test_metric.py
Labels: size:L

#1529 feat: translate instruction when adapting prompt
  src/ragas/prompt/mixin.py
  src/ragas/prompt/pydantic_prompt.py
Labels: size:S

#1535 chore: remove old prompt object
  src/ragas/llms/base.py
  src/ragas/llms/json_load.py
  src/ragas/llms/output_parser.py
  src/ragas/llms/prompt.py
  src/ragas/metrics/_faithfulness.py
  src/ragas/prompt/base.py
  src/ragas/prompt/pydantic_prompt.py
  src/ragas/utils.py
  tests/unit/llms/test_prompt_old.py
  tests/unit/prompt/test_prompt_utils.py
  tests/unit/test_analytics.py
  tests/unit/test_prompt.py
  tests/unit/test_testset_schema.py
Labels: size:XL

#1536 feat: improved the testset generation to_pandas and docs
  docs/getstarted/rag_evaluation.md
  docs/getstarted/rag_testset_generation.md
  docs/getstarted/raga_evaluation_output.png
  docs/getstarted/testset_output.png
  src/ragas/dataset_schema.py
  src/ragas/testset/synthesizers/generate.py
  src/ragas/testset/synthesizers/testset_schema.py
  src/ragas/testset/transforms/__init__.py
  src/ragas/testset/transforms/default.py
Labels: size:L

#1542 fixed typo in "single_turn_ascore"
  docs/howtos/migrations/migrate_from_v01_to_v02.md
Labels: size:XS

#1547 update AspectCritic docs examples
  docs/concepts/metrics/available_metrics/aspect_critic.md
  docs/concepts/metrics/available_metrics/general_purpose.md
Labels: size:M

#1541 Fix: Resolve Agentic failure loop with improved json parsing
  src/ragas/prompt/pydantic_prompt.py
  src/ragas/prompt/utils.py
  tests/unit/prompt/test_prompt_utils.py
Labels: size:L

#1549 feat: throw error when max_token limit is reached
  src/ragas/callbacks.py
  src/ragas/exceptions.py
  src/ragas/llms/base.py
Labels: size:L

#1550 Added community blog posts in Japanese
  docs/community/index.md
Labels: size:XS

#1553 docs: make llms and embeddings explicit
  docs/extra/components/choose_evaluator_llm.md
  docs/extra/components/choose_generator_llm.md
  docs/getstarted/rag_evaluation.md
  docs/getstarted/rag_testset_generation.md
Labels: size:M

#1560 feat: measure cost of testset generator
  docs/getstarted/rag_testset_generation.md
  docs/howtos/applications/_cost.md
  docs/howtos/applications/cost.ipynb
  src/ragas/dataset_schema.py
  src/ragas/testset/synthesizers/base_query.py
  src/ragas/testset/synthesizers/generate.py
  src/ragas/testset/synthesizers/specific_query.py
  src/ragas/testset/synthesizers/testset_schema.py
  src/ragas/testset/transforms/engine.py
  tests/unit/test_dataset_schema.py
Labels: size:L

#1554 docs: added luka's blogs
  docs/community/index.md
Labels: size:XS

#1561 Fix: add LLMContextPrecisionWithReference to __init__.py
  src/ragas/metrics/__init__.py
Labels: size:XS

#1562 add embeddings to TestsetGenerator
  src/ragas/testset/synthesizers/generate.py
Labels: size:M

#1569 Fix: Limit number of retries for parse failures
  src/ragas/exceptions.py
  src/ragas/prompt/pydantic_prompt.py
  tests/unit/test_prompt.py
Labels: size:M

#1570 Fix: reference key error in LLMContextPrecisionWithoutReference
  src/ragas/metrics/_context_precision.py
Labels: size:S

#1559 Feat: add multimodal eval support
  docs/concepts/metrics/available_metrics/index.md
  docs/concepts/metrics/available_metrics/multi_modal_faithfulness.md
  docs/concepts/metrics/available_metrics/multi_modal_relevance.md
  src/ragas/exceptions.py
  src/ragas/metrics/__init__.py
  src/ragas/metrics/_multi_modal_faithfulness.py
  src/ragas/metrics/_multi_modal_relevance.py
  src/ragas/prompt/__init__.py
  src/ragas/prompt/multi_modal_prompt.py
  src/ragas/prompt/pydantic_prompt.py
  src/ragas/testset/synthesizers/generate.py
  tests/unit/test_prompt.py
Labels: size:XL

#1566 fix: add `reference_topics` as default required columns in `TopicAdherenceScore` #1564
  src/ragas/metrics/_topic_adherence.py
Labels: size:XS

#1580 fix: add reference tool call to required cols
  docs/concepts/metrics/available_metrics/agents.md
  src/ragas/metrics/_tool_call_accuracy.py
Labels: size:S

#1578 Improve efficiency in factual correctness for precision mode
  src/ragas/metrics/_factual_correctness.py
Labels: size:S

#1543 This commit implements the F-beta score metric
  src/ragas/metrics/__init__.py
  src/ragas/metrics/_answer_correctness.py
  src/ragas/metrics/_factual_correctness.py
  src/ragas/metrics/utils.py
  tests/unit/test_metric.py
Labels: size:L

#1583 fix: agent goal accuracy
  docs/concepts/metrics/available_metrics/agents.md
  src/ragas/metrics/_goal_accuracy.py
Labels: size:S

#1581 chores: fix pypi rendering
  pyproject.toml
Labels: size:XS

#1585 fix: typo: ROUGE is a metric, ROGUE is a scoundrel
  src/ragas/metrics/__init__.py
  src/ragas/metrics/_rouge_score.py
Labels: size:XS

#1605 Fix : Filename in the path
  docs/howtos/migrations/migrate_from_v01_to_v02.md
Labels: size:XS

#1603 fix: remove abstract class in Metric
  src/ragas/metrics/base.py
Labels: size:XS

#1595 Added pandas as a method for reading datasets
  src/ragas/dataset_schema.py
Labels: size:XS

#1584 fix: treat anthropic-direct API the same as bedrock in llamaindex wrapper
  src/ragas/llms/base.py
Labels: size:S
