Repository explodinggradients/ragas, pull requests merged in 2025-07, with the labels that each got.

#2097 Fix/docs upgrade shade 2
  .dockerignore
  .gitignore
  docs/INSTALL
  docs/_static/js/header_border.js
  docs/_static/js/toggle.js
  docs/extra/ragas-modern.css
  docs/index.md
  mkdocs.yml
  scripts/dev_docs.sh
Labels: size:L

#2086 feat: ragas evals CLI
  experimental/pyproject.toml
  experimental/ragas_experimental/cli.py
  experimental/ragas_experimental/dataset.py
  experimental/ragas_experimental/metric/base.py
  experimental/ragas_experimental/metric/ranking.py
  experimental/ragas_experimental/project/backends/local_csv.py
  experimental/ragas_experimental/utils.py
Labels: size:XL

#2109 examples : example evals
  docs/experimental/backends/factory.html.md
  docs/experimental/backends/ragas_api_client.html.md
  docs/experimental/dataset.html.md
  docs/experimental/embedding/base.md
  docs/experimental/exceptions.html.md
  docs/experimental/experiment.html.md
  docs/experimental/explanation/index.md
  docs/experimental/index.md
  docs/experimental/init_module.md
  docs/experimental/llm/llm.html.md
  docs/experimental/metric/base.html.md
  docs/experimental/metric/decorator.html.md
  docs/experimental/metric/discrete.html.md
  docs/experimental/metric/numeric.html.md
  docs/experimental/metric/ranking.html.md
  docs/experimental/metric/result.html.md
  docs/experimental/model/pydantic_mode.html.md
  docs/experimental/project/core.html.md
  docs/experimental/project/experiments.html.md
  docs/experimental/project/naming.html.md
  docs/experimental/prompt/base.md
  docs/experimental/prompt/dynamic_few_shot.html.md
  docs/experimental/robots.txt
  docs/experimental/sitemap.xml
  docs/experimental/tracing/langfuse.html.md
  docs/experimental/tracing/mlflow.html.md
  docs/experimental/tutorials/agent.md
  docs/experimental/tutorials/index.md
  docs/experimental/tutorials/prompt.md
  docs/experimental/tutorials/rag.md
  docs/experimental/tutorials/workflow.md
  docs/experimental/typing.html.md
  docs/experimental/utils.html.md
  experimental/pyproject.toml
  experimental/ragas_examples/README.md
  experimental/ragas_examples/agent_evals/__init__.py
  experimental/ragas_examples/agent_evals/agent.py
  experimental/ragas_examples/agent_evals/evals.py
  experimental/ragas_examples/prompt_evals/__init__.py
  experimental/ragas_examples/prompt_evals/evals.py
  experimental/ragas_examples/prompt_evals/prompt.py
  experimental/ragas_examples/rag_eval/__init__.py
  experimental/ragas_examples/rag_eval/evals.py
  experimental/ragas_examples/rag_eval/rag.py
  experimental/ragas_examples/workflow_eval/__init__.py
  experimental/ragas_examples/workflow_eval/evals.py
  experimental/ragas_examples/workflow_eval/workflow.py
  experimental/ragas_experimental/experiment.py
Labels: size:XXL

#2114 docs: hello world & explanation
  docs/experimental/explanation/datasets.md
  docs/experimental/explanation/experimentation.md
  docs/experimental/explanation/index.md
  docs/experimental/explanation/metrics.md
  docs/experimental/index.md
Labels: size:L

#2119 chore: added `ragas.experimental` and cleaned dependencies
  experimental/pyproject.toml
  ragas/pyproject.toml
  ragas/src/ragas/__init__.py
  ragas/src/ragas/experimental/__init__.py
Labels: size:M

#2116 fix: metric alignment with `inmemory` backend
  experimental/pyproject.toml
  experimental/ragas_experimental/backends/inmemory.py
  experimental/ragas_experimental/dataset.py
  experimental/ragas_experimental/metrics/base.py
  experimental/tests/unit/backends/test_inmemory.py
Labels: size:XXL

#2120 docs: added structure to sidebar
  docs/experimental/core_concepts/datasets.md
  docs/experimental/core_concepts/experimentation.md
  docs/experimental/core_concepts/index.md
  docs/experimental/core_concepts/metrics.md
  docs/experimental/index.md
  mkdocs.yml
Labels: size:S

#2127 docs: improve hello world
  docs/experimental/explanation/datasets.md
  docs/experimental/explanation/experimentation.md
  docs/experimental/explanation/index.md
  docs/experimental/explanation/metrics.md
  docs/experimental/hello_world.gif
  docs/experimental/index.md
  docs/experimental/output_first_experiment.png
  experimental/ragas_experimental/backends/README.md
Labels: size:M

#2129 examples: fix api changes
  experimental/ragas_examples/agent_evals/evals.py
  experimental/ragas_examples/prompt_evals/evals.py
  experimental/ragas_examples/rag_eval/evals.py
  experimental/ragas_examples/workflow_eval/evals.py
Labels: size:M
