Repository explodinggradients/ragas, pull requests merged in 2025-08, with the labels that each got.

#2156 Fix experimental docs navigation, fix broken tutorials, improve examples for better user understanding
  docs/experimental/core_concepts/datasets.md
  docs/experimental/core_concepts/experimentation.md
  docs/experimental/core_concepts/index.md
  docs/experimental/core_concepts/metrics.md
  docs/experimental/index.md
  docs/experimental/tutorials/agent.md
  docs/experimental/tutorials/prompt.md
  docs/experimental/tutorials/rag.md
  docs/experimental/tutorials/workflow.md
  experimental/ragas_examples/agent_evals/evals.py
  experimental/ragas_examples/rag_eval/evals.py
  experimental/ragas_examples/rag_eval/rag.py
  experimental/ragas_examples/workflow_eval/evals.py
  experimental/ragas_examples/workflow_eval/workflow.py
  mkdocs.yml
Labels: size:L

#2163 refactor: use basemetric as base for metric
  experimental/ragas_experimental/metrics/base.py
Labels: size:S

#2164 add: pre-commit hook to run ci on every commit
  .pre-commit-config.yaml
  DEVELOPMENT.md
  Makefile
  experimental/pyproject.toml
  ragas/pyproject.toml
Labels: size:S

#2169 Add python 3.13 target, refactor on pre-commit and benchmarking tests
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  Makefile
Labels: size:XS

#2137 fix: enum values instead of names in testset synthesizers
  ragas/src/ragas/testset/synthesizers/multi_hop/base.py
  ragas/src/ragas/testset/synthesizers/single_hop/base.py
Labels: size:XS

#2176 Move Examples to root
  .gitignore
  examples/README.md
  examples/agent_evals/__init__.py
  examples/agent_evals/agent.py
  examples/agent_evals/evals.py
  examples/gdrive_append_example.py
  examples/gdrive_backend_example.py
  examples/prompt_evals/__init__.py
  examples/prompt_evals/evals.py
  examples/prompt_evals/prompt.py
  examples/rag_eval/__init__.py
  examples/rag_eval/evals.py
  examples/rag_eval/rag.py
  examples/workflow_eval/__init__.py
  examples/workflow_eval/evals.py
  examples/workflow_eval/workflow.py
  ragas/examples/experimental/README.md
Labels: size:M

#2180 Remove txt requirements
  .github/workflows/ci.yaml
  requirements/dev.txt
  requirements/docs.txt
  requirements/gdrive.txt
  requirements/test.txt
Labels: size:M

#2175 feat: move `experiment` from experimental to ragas main
  .github/workflows/ci.yaml
  CLAUDE.md
  docs/experimental/core_concepts/experimentation.md
  docs/experimental/index.md
  docs/experimental/tutorials/agent.md
  docs/experimental/tutorials/prompt.md
  docs/experimental/tutorials/workflow.md
  examples/agent_evals/evals.py
  examples/prompt_evals/evals.py
  examples/rag_eval/evals.py
  examples/workflow_eval/evals.py
  ragas/src/ragas/__init__.py
  ragas/src/ragas/experiment.py
  ragas/src/ragas/experimental/__init__.py
  ragas/src/ragas/utils.py
  ragas/tests/experimental/unit/test_datatable.py
  ragas/tests/unit/test_experiment.py
Labels: size:XL

#2199 fix: setup and local ci
  CLAUDE.md
  Makefile
  ragas/Makefile
Labels: size:L

#2158 Docs/how-to-benchmark-new-llm-guide
  .cursor/rules/docs-diataxis-guidelines.mdc
  .cursor/rules/docs-structure.mdc
  .cursor/rules/project-structure.mdc
  .cursor/rules/use-uv-cli.mdc
  .gitignore
  docs/experimental/howtos/benchmark_llm.md
  docs/experimental/howtos/index.md
  docs/experimental/index.md
  experimental/ragas_examples/benchmark_llm/__init__.py
  experimental/ragas_examples/benchmark_llm/datasets/discount_benchmark.csv
  experimental/ragas_examples/benchmark_llm/evals.py
  experimental/ragas_examples/benchmark_llm/prompt.py
  mkdocs.yml
Labels: documentation, size:XL

#2197 Move `prompts` to ragas
  docs/concepts/components/prompt.md
  ragas/src/ragas/experimental/metrics/base.py
  ragas/src/ragas/experimental/prompt/__init__.py
  ragas/src/ragas/integrations/tracing/__init__.py
  ragas/src/ragas/integrations/tracing/langfuse.py
  ragas/src/ragas/prompt/__init__.py
  ragas/src/ragas/prompt/dynamic_few_shot.py
  ragas/src/ragas/prompt/prompt-formats.md
  ragas/src/ragas/prompt/simple_prompt.py
  ragas/tests/e2e/test_testset_generation.py
  ragas/tests/unit/prompt/test_dynamic_few_shot_prompt.py
  ragas/tests/unit/prompt/test_prompt_save_load.py
  workspace.toml
Labels: size:L

#2206 refactor: removing some section to streamline pr template
  .github/pull_request_template.md
  .github/workflows/claude-code-review.yml
Labels: size:M

#2213 fix: _version.py is to be ignored in git
  .gitignore
  src/ragas/_version.py
Labels: size:M

#2081 Fix a couple of typos in `docs/getstarted/evals.md`
  docs/getstarted/evals.md
Labels: size:XS

#2216 Fix repeating template bug in _nv_metrics.py
  src/ragas/metrics/_nv_metrics.py
Labels: size:XS

#2215 fix: ragas dir structure path fixes
  .cursor/rules/project-structure.mdc
  CLAUDE.md
  DEVELOPMENT.md
  README.md
  docs/INSTALL
  mkdocs.yml
  scripts/dev_docs.sh
Labels: size:L

#1947 fix: update docstrings for single-hop use case
  src/ragas/testset/synthesizers/single_hop/base.py
  src/ragas/testset/synthesizers/single_hop/specific.py
Labels: size:XS

#1977 Fix issue with cache hits
  src/ragas/cache.py
  tests/unit/test_cache.py
Labels: size:S

#1978 Use generate_multiple instead of generate in a loop in ResponseRelevancy
  src/ragas/metrics/_answer_relevance.py
Labels: size:S

#2008 fix: update required columns in RefusalRate (docs)
  docs/howtos/customizations/metrics/_write_your_own_metric_advanced.md
Labels: size:XS

#2218 Add support for make install-minimal to speed up CI + dev
  .github/workflows/ci.yaml
  CLAUDE.md
  DEVELOPMENT.md
  Makefile
  examples/benchmark_llm/evals.py
  examples/gdrive_append_example.py
  pyproject.toml
Labels: size:L

#2037 update compare_embeddings doc links
  docs/howtos/applications/compare_embeddings.md
Labels: size:XS

#2223 Retire `ragas.experimental` namespace
  .github/workflows/ci.yaml
  CLAUDE.md
  DEVELOPMENT.md
  Makefile
  examples/agent_evals/evals.py
  examples/prompt_evals/evals.py
  examples/rag_eval/evals.py
  examples/workflow_eval/evals.py
  pyproject.toml
  scripts/process_experimental_notebooks.py
  src/ragas/cli.py
  tests/conftest.py
  tests/experimental/__init__.py
  tests/experimental/conftest.py
  tests/experimental/e2e/__init__.py
  tests/experimental/unit/__init__.py
  tests/experimental/unit/test_metric_base.py
  tests/unit/llms/test_instructor_factory.py
  tests/unit/test_datatable_inheritance.py
  tests/unit/test_metric.py
Labels: size:XL

#2224 chore: cleanup docs for ragas directory
  DEVELOPMENT.md
  docs/getstarted/install.md
Labels: size:XS

#2217 fix: update make commands to use uv for docs
  Makefile
Labels: size:XS

#2230 security: stop supporting v0.2 security releases
  SECURITY.md
Labels: size:S

#2121 Fixed the mermaid which was breaking on navigation
  .gitignore
Labels: size:XS

#2232 chore: added reo.js analytics
  docs/_static/js/octolane.js
  docs/_static/js/reo.js
  mkdocs.yml
Labels: size:S

#2235 Move tutorials
  docs/tutorials/agent.md
  docs/tutorials/index.md
  docs/tutorials/prompt.md
  docs/tutorials/rag.md
  docs/tutorials/workflow.md
Labels: size:S

#2236 Move howtos
  docs/experimental/howtos/index.md
  docs/howtos/applications/benchmark_llm.md
  docs/howtos/customizations/iterate_prompt.md
  mkdocs.yml
Labels: size:M
