Repository explodinggradients/ragas, pull requests merged in 2025-06, with the labels that each got.

#2062 feat: user simulator
  experimental/ragas_experimental/simulation.py
Labels: size:L

#2059 Update analytics source
  README.md
Labels: size:XS

#2069 feat: check embedding shapes in CosineSimilarityBuilders
  ragas/src/ragas/testset/transforms/relationship_builders/cosine.py
Labels: size:S

#2084 feat: llm as prompt as optional
  experimental/ragas_experimental/metric/base.py
  experimental/ragas_experimental/metric/decorator.py
  experimental/ragas_experimental/metric/discrete.py
  experimental/ragas_experimental/metric/numeric.py
  experimental/ragas_experimental/metric/ranking.py
  experimental/ragas_experimental/metric/result.py
Labels: size:L
