Repository explodinggradients/ragas, pull requests merged in 2025-03, with the labels that each got.

#1940 nvidia docs
  docs/concepts/metrics/available_metrics/index.md
  docs/concepts/metrics/available_metrics/nvidia_metrics.md
  mkdocs.yml
  src/ragas/metrics/_nv_metrics.py
  src/ragas/metrics/base.py
Labels: size:L

#1943 unnecessary Noise Sensitivity name update
  src/ragas/metrics/_noise_sensitivity.py
Labels: size:XS

#1926 When saving kg only save the node id in the relationships
  src/ragas/testset/graph.py
Labels: size:S

#1934 Update default.py - Missing `cosine_similarity` transform for docs with Token Count 101–500
  src/ragas/testset/transforms/default.py
Labels: size:XS

#1924 Ndarray dtype fix, improve error wording
  src/ragas/exceptions.py
  src/ragas/metrics/_factual_correctness.py
Labels: size:S

#1957 md of vertexai notebooks
  docs/_static/annotated_data.json
  docs/_static/bar_plot.png
  docs/_static/radar_plot.png
  docs/howtos/applications/index.md
  docs/howtos/applications/vertexai_alignment.md
  docs/howtos/applications/vertexai_model_comparision.md
  docs/howtos/applications/vertexai_x_ragas.md
  mkdocs.yml
Labels: size:XXL

#1959 Single-hop query testset generation tutorial
  docs/howtos/applications/index.md
  docs/howtos/applications/singlehop_testset_gen.md
  mkdocs.yml
Labels: size:L

#1974 AWS Bedrock Integration
  docs/_static/architecture.png
  docs/howtos/integrations/aws_bedrock.md
  docs/howtos/integrations/index.md
  mkdocs.yml
  src/ragas/embeddings/haystack_wrapper.py
  src/ragas/integrations/aws_bedrock.py
  src/ragas/integrations/langchain.py
  src/ragas/metrics/_answer_similarity.py
  src/ragas/optimizers/genetic.py
  src/ragas/prompt/few_shot_pydantic_prompt.py
  src/ragas/testset/graph.py
  tests/unit/test_knowledge_graph_save.py
Labels: size:XXL

#1984 Benchmarking Tutorial
  docs/_static/qasper_data_collection.png
  docs/howtos/applications/gemini_benchmarking.md
  docs/howtos/applications/index.md
  mkdocs.yml
Labels: size:XXL
