Repository explodinggradients/ragas, pull requests merged in 2025-09, with the labels that each got.

#2030 feature!: knowledge graph flexibility
  src/ragas/testset/synthesizers/multi_hop/abstract.py
  src/ragas/testset/synthesizers/multi_hop/specific.py
  src/ragas/testset/synthesizers/single_hop/specific.py
  tests/unit/test_analytics.py
Labels: size:M

#1894 return False when pred_sequence length and ref_requence length is dif…
  src/ragas/metrics/_tool_call_accuracy.py
Labels: size:XS, blocked

#2244 Add deprecation warnings for embeddings
  docs/extra/components/choose_evaluator_llm.md
  docs/extra/components/choose_generator_llm.md
  docs/getstarted/rag_eval.md
  docs/howtos/applications/compare_embeddings.md
  docs/howtos/applications/singlehop_testset_gen.md
  docs/howtos/customizations/testgenerator/_language_adaptation.md
  docs/howtos/customizations/testgenerator/_testgen-custom-single-hop.md
  docs/howtos/customizations/testgenerator/_testgen-customisation.md
  docs/howtos/customizations/testgenerator/language_adaptation.ipynb
  docs/howtos/customizations/testgenerator/testgen-custom-single-hop.ipynb
  docs/howtos/customizations/testgenerator/testgen-customisation.ipynb
  docs/howtos/integrations/langchain.md
  docs/howtos/observability.md
  examples/gdrive_backend_example.py
  examples/iterate_prompt/evals.py
  examples/iterate_prompt/run_prompt.py
  examples/ragas_examples/__init__.py
  examples/ragas_examples/agent_evals/evals.py
  examples/ragas_examples/benchmark_llm/evals.py
  examples/ragas_examples/prompt_evals/evals.py
  examples/ragas_examples/rag_eval/evals.py
  examples/ragas_examples/workflow_eval/evals.py
  src/ragas/embeddings/__init__.py
  src/ragas/embeddings/base.py
Labels: size:L

#2238 docs: fix broken link in FAQ (metrics tracing)
  docs/index.md
Labels: size:XS

#2242 feat: cancellable task
  docs/howtos/customizations/cancellation.md
  docs/howtos/customizations/index.md
  mkdocs.yml
  src/ragas/evaluation.py
  src/ragas/executor.py
  src/ragas/integrations/llama_index.py
  src/ragas/optimizers/genetic.py
  src/ragas/testset/synthesizers/generate.py
  tests/unit/test_cancellation.py
Labels: size:XL

#2248 update: add og images and metadata to docs
  docs/extra/overrides/main.html
  mkdocs.yml
Labels: size:M

#2229 fix: add support for both langchain llm and ragas llm
  .gitignore
  src/ragas/prompt/multi_modal_prompt.py
  src/ragas/prompt/pydantic_prompt.py
Labels: size:L

#2250 chore: analytics support for commonroom and scarf
  README.md
  docs/_static/js/commonroom.js
  docs/extra/overrides/main.html
  mkdocs.yml
Labels: size:M

#2262 Update context_precision.md
  docs/concepts/metrics/available_metrics/context_precision.md
Labels: size:M

#2272 Fix docs: correct inheritance class for Non-LLM metrics
  docs/concepts/metrics/overview/index.md
Labels: size:XS

#2273 added rb2b analytics
  docs/_static/js/rb2b.js
  mkdocs.yml
Labels: size:XS

#2278 removed some meta properties to test
  docs/extra/overrides/main.html
  mkdocs.yml
Labels: size:M

#2070 feature: improve async / executor functionality
  docs/references/executor.md
  src/ragas/async_utils.py
  src/ragas/executor.py
  src/ragas/metrics/base.py
  src/ragas/testset/transforms/base.py
  src/ragas/testset/transforms/engine.py
  src/ragas/utils.py
  tests/unit/test_async_utils.py
  tests/unit/test_engine.py
  tests/unit/test_executor.py
  tests/unit/test_executor_in_jupyter.ipynb
Labels: size:XXL

#2270 Remove experimental from docs and fix examples in docs
  docs/_static/imgs/experiments_quickstart/hello_world.gif
  docs/_static/imgs/experiments_quickstart/output_first_experiment.png
  docs/concepts/experimentation.md
  docs/experimental/core_concepts/index.md
  docs/experimental/howtos/index.md
  docs/getstarted/experiments_quickstart.md
  docs/getstarted/index.md
  examples/iterate_prompt/evals.py
  examples/ragas_examples/agent_evals/agent.py
  examples/ragas_examples/agent_evals/evals.py
  examples/ragas_examples/benchmark_llm/evals.py
  mkdocs.yml
Labels: size:L

#2258 fix: resolve TypeError in TopicAdherenceScore bitwise operations
  src/ragas/metrics/_topic_adherence.py
Labels: size:M

#2267 Knowledge graph/optimize for large corpus
  .gitignore
  src/ragas/testset/graph.py
  src/ragas/testset/synthesizers/multi_hop/abstract.py
  tests/unit/test_graph.py
  tests/unit/test_knowledge_graph_clusters.py
  tests/unit/test_knowledge_graph_save.py
  tests/unit/test_multi_hop_query_synthesizer.py
Labels: size:XXL

#2260 Add telemetry
  src/ragas/_analytics.py
  src/ragas/embeddings/base.py
  src/ragas/embeddings/openai_provider.py
  src/ragas/llms/base.py
  src/ragas/prompt/few_shot_pydantic_prompt.py
  src/ragas/prompt/pydantic_prompt.py
  src/ragas/prompt/simple_prompt.py
Labels: size:L

#2287 OpenAI model cost
  src/ragas/cost.py
  tests/unit/test_cost.py
Labels: size:M

#1983 docs: agent metrics code examples improvement
  docs/concepts/metrics/available_metrics/agents.md
Labels: size:L

#1993 Prompt Optimization Tutorial
  docs/howtos/applications/index.md
  docs/howtos/applications/prompt_optimization.md
  mkdocs.yml
Labels: size:L

#2290 fix: removed the need for regex patterns
  examples/pyproject.toml
Labels: size:XS

#2294 Fix/asyncio
  docs/getstarted/evals.md
  docs/references/aevaluate.md
  docs/references/evaluate.md
  mkdocs.yml
  src/ragas/__init__.py
  src/ragas/async_utils.py
  src/ragas/evaluation.py
  src/ragas/utils.py
  tests/unit/test_async_evaluation.py
  tests/unit/test_cache.py
  tests/unit/test_import.py
Labels: size:XL

#2240 Refactor/update gemini to genai sdk
  src/ragas/llms/base.py
  tests/unit/llms/test_instructor_factory.py
Labels: size:S

#2298 Feature/metrics input flexibility
  src/ragas/metrics/base.py
  tests/unit/test_metric.py
Labels: size:L

#2295 Ensure old_temperature is set correctly. Fixes #1937 and #2110
  src/ragas/llms/base.py
Labels: size:XS

#2299 Tokens counting
  src/ragas/testset/transforms/splitters/headline.py
Labels: size:M

#2307 Metric/parallel tool call
  src/ragas/metrics/_tool_call_accuracy.py
  tests/unit/test_tool_call_accuracy.py
Labels: size:L

#2308 Fix: avoid ambiguous truth value for empty numpy array in HuggingfaceEmbeddings (fixes #2080)
  src/ragas/embeddings/base.py
Labels: size:XS

#2309 Devpod cn/main
  docs/concepts/metrics/available_metrics/context_precision.md
  docs/concepts/metrics/available_metrics/context_recall.md
  src/ragas/dataset_schema.py
  src/ragas/metrics/__init__.py
  src/ragas/metrics/_context_precision.py
  src/ragas/metrics/_context_recall.py
Labels: size:L

#2311 Feat/quoted spans metric
  docs/quoted_spans_metric.md
  src/ragas/metrics/quoted_spans.py
  tests/test_quoted_spans.py
Labels: size:L

#2293 Docs/eval_rag_agent - how to evaluate and improve rag app
  .cursor/commands/git-pr.md
  .cursor/rules/update-guide.mdc
  .gitignore
  docs/_static/imgs/howto_improve_rag_mlflow.png
  docs/howtos/applications/evaluate-and-improve-rag.md
  docs/howtos/applications/index.md
  examples/pyproject.toml
  examples/ragas_examples/improve_rag/__init__.py
  examples/ragas_examples/improve_rag/datasets/hf_doc_qa_eval.csv
  examples/ragas_examples/improve_rag/evals.py
  examples/ragas_examples/improve_rag/rag.py
  examples/ragas_examples/text2sql/__init__.py
  mkdocs.yml
Labels: size:XXL

#2328 fix: concurrent ResponseRelevancy
  src/ragas/prompt/pydantic_prompt.py
Labels: size:S

#2321 feat: Add OCI Gen AI Integration for Direct LLM Support
  docs/howtos/integrations/index.md
  docs/howtos/integrations/oci_genai.md
  examples/oci_genai_example.py
  mkdocs.yml
  pyproject.toml
  src/ragas/llms/__init__.py
  src/ragas/llms/oci_genai_wrapper.py
  tests/unit/test_oci_genai_wrapper.py
Labels: size:XXL
