Repository explodinggradients/ragas, pull requests merged in 2025-02, with the labels that each got.

#1891 Remove llm argument from ToolCallAccuracy initialization
  docs/concepts/metrics/available_metrics/agents.md
  docs/howtos/integrations/_langgraph_agent_evaluation.md
  docs/howtos/integrations/langgraph_agent_evaluation.ipynb
  docs/howtos/integrations/swarm_agent_evaluation.md
Labels: size:XS

#1899 Updated Application Page
  docs/howtos/applications/_metrics_llm_calls.md
  docs/howtos/applications/metrics_llm_calls.ipynb
  docs/howtos/applications/metrics_llm_calls.png
  docs/howtos/integrations/haystack.ipynb
  src/ragas/integrations/langgraph.py
  src/ragas/llms/base.py
  src/ragas/utils.py
Labels: size:L

#1903 feat: add http request-response logging with env flag control
  src/ragas/sdk.py
Labels: size:M

#1908 Metric with different parameter gives different score
  docs/concepts/metrics/available_metrics/noise_sensitivity.md
  docs/concepts/metrics/available_metrics/traditional.md
  src/ragas/evaluation.py
  src/ragas/metrics/_noise_sensitivity.py
  src/ragas/metrics/_rouge_score.py
  src/ragas/metrics/base.py
  src/ragas/sdk.py
Labels: size:M

#1906 Updated the instruction of `StatementGeneratorPrompt` in faithfulness
  src/ragas/metrics/_faithfulness.py
Labels: size:XS

#1919 Evaluating Multi-Turn Conversations
  docs/howtos/applications/evaluating_multi_turn_conversations.md
  docs/howtos/applications/index.md
  docs/howtos/customizations/testgenerator/_testgen-custom-single-hop.md
  mkdocs.yml
Labels: size:L

#1921 fix SingleHopQuerySynthesizer::prepare_combinations()
  src/ragas/testset/synthesizers/single_hop/base.py
Labels: size:XS

#1910 docs: fix semantic similarity description (cross-encoder -> bi-encoder)
  docs/concepts/metrics/available_metrics/semantic_similarity.md
Labels: size:XS

#1920 docs: list googles model provider
  docs/extra/components/choose_evaluator_llm.md
  docs/extra/components/choose_generator_llm.md
Labels: size:L

#1929 Enable Runtime Checks for ModeMetric Protocol
  src/ragas/metrics/base.py
Labels: size:XS

#1918 r2r integration
  docs/_static/r2r_integration_ragas_app.png
  docs/concepts/test_data_generation/rag.md
  docs/howtos/integrations/index.md
  docs/howtos/integrations/r2r.md
  docs/howtos/integrations/swarm_agent_evaluation.md
  mkdocs.yml
  pyproject.toml
  requirements/dev.txt
  src/ragas/integrations/r2r.py
Labels: size:L

#1901 Haystack llm and embedding wrapper
  pyproject.toml
  requirements/dev.txt
  src/ragas/embeddings/__init__.py
  src/ragas/embeddings/base.py
  src/ragas/embeddings/haystack_wrapper.py
  src/ragas/llms/__init__.py
  src/ragas/llms/base.py
  src/ragas/llms/haystack_wrapper.py
  tests/unit/test_import.py
Labels: size:L
