Repository explodinggradients/ragas, pull requests merged in 2025-10, with the labels that each got.

#2320 feat: Add save/load functionality and improved repr for LLM-based metrics
  src/ragas/metrics/base.py
  src/ragas/metrics/decorator.py
  src/ragas/metrics/discrete.py
  src/ragas/metrics/numeric.py
  src/ragas/metrics/ranking.py
  src/ragas/metrics/validators.py
  tests/unit/test_simple_llm_metric_persistence.py
Labels: size:XL

#2333 refactor: docs and warnings for metric base new structure
  src/ragas/metrics/base.py
  src/ragas/metrics/decorator.py
  src/ragas/metrics/discrete.py
  src/ragas/metrics/numeric.py
  src/ragas/metrics/ranking.py
  src/ragas/metrics/validators.py
  tests/unit/test_simple_llm_metric_persistence.py
Labels: size:L

#2319 Simplify earlier how to guides in docs
  docs/howtos/applications/benchmark_llm.md
  docs/howtos/applications/gemini_benchmarking.md
  docs/howtos/applications/index.md
  docs/howtos/applications/text2sql.md
  examples/iterate_prompt/evals.py
  examples/iterate_prompt/run_prompt.py
  examples/ragas_examples/agent_evals/evals.py
  examples/ragas_examples/benchmark_llm/evals.py
  examples/ragas_examples/benchmark_llm/prompt.py
  examples/ragas_examples/improve_rag/evals.py
  examples/ragas_examples/text2sql/__init__.py
  examples/ragas_examples/text2sql/analyze_errors.py
  examples/ragas_examples/text2sql/data_utils.py
  examples/ragas_examples/text2sql/db_utils.py
  examples/ragas_examples/text2sql/evals.py
  examples/ragas_examples/text2sql/text2sql_agent.py
  mkdocs.yml
Labels: size:XXL

#2346 docs: reorganize prompt evaluation guides in navigation
  docs/howtos/applications/index.md
  docs/howtos/applications/iterate_prompt.md
  mkdocs.yml
Labels: size:S
