Repository explodinggradients/ragas, pull requests merged in 2025-04, with the labels that each got.

#1987 Create SECURITY.md
  SECURITY.md
Labels: size:M

#1965 Evaluation function documentation improvements
  src/ragas/evaluation.py
Labels: size:M

#1966 directory name change in docs
  docs/howtos/applications/singlehop_testset_gen.md
Labels: size:XS

#1986 Detailed error message for noise sensitivity metric
  src/ragas/metrics/_noise_sensitivity.py
Labels: size:S

#1971 Docs: Fixed broken links in nav bar for NVIDIA metrics
  mkdocs.yml
Labels: size:XS

#1982 Refactor: Update AWS Bedrock Naming to Amazon Bedrock Across Docs & Repo Structure
  docs/howtos/integrations/amazon_bedrock.md
  docs/howtos/integrations/index.md
  mkdocs.yml
  src/ragas/embeddings/base.py
  src/ragas/integrations/amazon_bedrock.py
Labels: size:M

#2011 LlamaStack integration
  docs/howtos/integrations/index.md
  docs/howtos/integrations/llama_stack.md
  mkdocs.yml
  src/ragas/embeddings/base.py
  src/ragas/evaluation.py
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/_noise_sensitivity.py
Labels: size:L

#2003 Adding the link to download the utils and minor changes
  docs/howtos/integrations/amazon_bedrock.md
Labels: size:S

#2017 Enhance MultiTurnSample Validator to Support Multiple Tool Calls
  src/ragas/dataset_schema.py
Labels: size:M

#2021 Griptape integration
  docs/howtos/integrations/griptape.md
  docs/howtos/integrations/index.md
  mkdocs.yml
  src/ragas/integrations/griptape.py
Labels: size:L

#2016 Fix shared examples bug in FactualCorrectness metric
  src/ragas/metrics/_factual_correctness.py
Labels: size:S

#2020 docs: removed SUPPORTED_LANGUAGE
  docs/howtos/customizations/metrics/metrics_language_adaptation.ipynb
Labels: size:S

#2023 docs: add CTA for Ragas app
  README.md
  docs/_static/ragas_app.gif
  docs/getstarted/evals.md
  docs/getstarted/rag_eval.md
  docs/getstarted/rag_testset_generation.md
  docs/howtos/applications/_metrics_llm_calls.md
  docs/howtos/applications/metrics_llm_calls.ipynb
  docs/howtos/customizations/metrics/train_your_own_metric.md
  docs/howtos/integrations/langchain.md
  mkdocs.yml
Labels: size:XL
