Repository explodinggradients/ragas, pull requests merged in 2025-01, with the labels that each got.

#1804 fix: llamaindex testset generator
  README.md
  docs/howtos/integrations/_llamaindex.md
  docs/howtos/integrations/llamaindex.ipynb
  src/ragas/testset/synthesizers/generate.py
Labels: size:L

#1805 Docs improvements
  docs/concepts/metrics/available_metrics/agents.md
  docs/concepts/metrics/available_metrics/answer_relevance.md
  docs/concepts/metrics/available_metrics/context_precision.md
  docs/concepts/metrics/available_metrics/factual_correctness.md
  docs/concepts/metrics/available_metrics/noise_sensitivity.md
  docs/howtos/customizations/metrics/_write_your_own_metric_advanced.md
Labels: size:S

#1808 Docs improvements
  docs/concepts/metrics/available_metrics/general_purpose.md
Labels: size:XS

#1811 Fix typo in index.md
  docs/howtos/applications/index.md
Labels: size:XS

#1816 docs: clean get-started
  docs/getstarted/evals.md
  docs/getstarted/index.md
  docs/getstarted/rag_eval.md
  docs/getstarted/rag_evaluation.md
  docs/getstarted/rag_testset_generation.md
Labels: size:M

#1810 Improve question generation efficiency In Response Relevancy metrics
  src/ragas/metrics/_answer_relevance.py
Labels: size:S

#1820 fix: add min requirement for optimisation
  src/ragas/optimizers/genetic.py
Labels: size:S

#1795 Added from_url method to fetch evaluation annotation from the api.
  src/ragas/dataset_schema.py
  src/ragas/metrics/base.py
  src/ragas/sdk.py
  src/ragas/testset/synthesizers/testset_schema.py
Labels: size:L

#1824 docs: fix incorrect imports
  docs/concepts/metrics/available_metrics/faithfulness.md
  docs/concepts/metrics/available_metrics/multi_modal_faithfulness.md
  docs/concepts/metrics/available_metrics/multi_modal_relevance.md
Labels: size:XS

#1825 docs: update some misc doc errors
  docs/concepts/metrics/overview/index.md
  docs/index.md
  docs/references/index.md
  mkdocs.yml
Labels: size:M

#1827 Feat: Fix for Instance Based Metrics and Updated docs
  docs/concepts/metrics/available_metrics/general_purpose.md
  docs/concepts/metrics/available_metrics/semantic_similarity.md
  src/ragas/metrics/_instance_specific_rubrics.py
  src/ragas/metrics/_simple_criteria.py
Labels: size:M

#1828 Docs/updating the LangSmith docs
  docs/_static/langsmith_dashboard.png
  docs/howtos/integrations/_langsmith.md
  docs/howtos/integrations/langsmith.md
  mkdocs.yml
  src/ragas/metrics/_answer_relevance.py
  src/ragas/sdk.py
  src/ragas/testset/synthesizers/testset_schema.py
Labels: size:L

#1826 fix: remove pysbd and sentence segmenting
  pyproject.toml
  src/ragas/metrics/_answer_correctness.py
  src/ragas/metrics/_bleu_score.py
  src/ragas/metrics/_factual_correctness.py
  src/ragas/metrics/_faithfulness.py
  src/ragas/metrics/_noise_sensitivity.py
  src/ragas/metrics/base.py
  src/ragas/prompt/base.py
  src/ragas/prompt/mixin.py
  src/ragas/prompt/pydantic_prompt.py
  src/ragas/utils.py
Labels: size:L

#1830 docs: Fixed most of the broken links
  docs/concepts/components/eval_dataset.md
  docs/concepts/index.md
  docs/concepts/metrics/overview/index.md
  docs/concepts/test_data_generation/rag.md
  docs/extra/components/choose_evaluator_llm.md
  docs/extra/components/choose_generator_llm.md
  docs/getstarted/evals.md
  docs/getstarted/rag_eval.md
  docs/getstarted/rag_testset_generation.md
  docs/howtos/applications/_cost.md
  docs/howtos/applications/_metrics_llm_calls.md
  docs/howtos/applications/compare_llms.md
  docs/howtos/customizations/_run_config.md
  docs/howtos/customizations/metrics/_modifying-prompts-metrics.md
  docs/howtos/customizations/metrics/_write_your_own_metric.md
  docs/howtos/customizations/metrics/_write_your_own_metric_advanced.md
  docs/howtos/customizations/testgenerator/_testgen-custom-single-hop.md
  docs/howtos/customizations/testgenerator/_testgen-customisation.md
  docs/howtos/index.md
  docs/howtos/integrations/_llamaindex.md
  docs/howtos/integrations/_zeno.md
  docs/howtos/integrations/index.md
  docs/howtos/integrations/langchain.md
  docs/howtos/migrations/migrate_from_v01_to_v02.md
  docs/howtos/observability.md
Labels: size:XL

#1834 docs: updated the formula for some metrics
  docs/concepts/metrics/available_metrics/agents.md
  docs/concepts/metrics/available_metrics/answer_relevance.md
  docs/concepts/metrics/available_metrics/aspect_critic.md
  docs/concepts/metrics/available_metrics/context_entities_recall.md
  docs/concepts/metrics/available_metrics/context_precision.md
  docs/concepts/metrics/available_metrics/context_recall.md
  docs/concepts/metrics/available_metrics/factual_correctness.md
  docs/concepts/metrics/available_metrics/faithfulness.md
  docs/concepts/metrics/available_metrics/general_purpose.md
  docs/concepts/metrics/available_metrics/noise_sensitivity.md
  docs/concepts/metrics/available_metrics/semantic_similarity.md
  docs/concepts/metrics/available_metrics/summarization_score.md
  docs/concepts/metrics/available_metrics/traditional.md
Labels: size:L

#1839 docs: update _language_adaptation.md
  docs/howtos/customizations/testgenerator/_language_adaptation.md
Labels: size:XS

#1843 feat: added option to provide experiment_name to evaluate()
  .readthedocs.yml
  src/ragas/dataset_schema.py
  src/ragas/evaluation.py
  src/ragas/metrics/_domain_specific_rubrics.py
  src/ragas/metrics/base.py
Labels: size:S

#1836 Change save and load encode to utf-8
  src/ragas/prompt/pydantic_prompt.py
Labels: size:XS

#1835 fix numpy invert error in metrics
  src/ragas/metrics/_factual_correctness.py
Labels: size:XS

#1845 Adding Swarm integration to the list of integrations
  docs/howtos/integrations/index.md
Labels: size:XS

#1837 Adjustment when calculating hash | Adjustment of the hash calculation…
  src/ragas/prompt/pydantic_prompt.py
Labels: size:M

#1846 docs: removed SUPPORTED_LANGUAGE
  docs/howtos/customizations/metrics/_metrics_language_adaptation.md
Labels: size:S

#1851 Add token parser for Bedrock & fix anthropic typo
  src/ragas/cost.py
  src/ragas/integrations/swarm.py
  src/ragas/llms/base.py
  src/ragas/prompt/pydantic_prompt.py
  tests/unit/test_cost.py
Labels: size:L

#1848 fix tp&fp calc error
  src/ragas/metrics/_factual_correctness.py
  src/ragas/testset/synthesizers/multi_hop/base.py
  src/ragas/testset/synthesizers/single_hop/base.py
Labels: size:S

#1858 docs: be consistent with the variable naming of `evaluator_embeddings`
  docs/concepts/metrics/available_metrics/answer_relevance.md
Labels: size:XS

#1862 Add optional use_effective_order parameter to BLEU score
  src/ragas/metrics/_bleu_score.py
Labels: size:XS

#1847 docs: updated broken links in ReadMe and evaluation documentation
  README.md
  docs/getstarted/evals.md
Labels: size:XS

#1863 docs: fix incorrect reference to LLM in NonLLMContextPrecisionWithReference metric
  docs/concepts/metrics/available_metrics/context_precision.md
  src/ragas/testset/synthesizers/multi_hop/base.py
  src/ragas/testset/synthesizers/single_hop/base.py
Labels: size:XS

#1864 fix: output parser bug
  src/ragas/prompt/pydantic_prompt.py
Labels: size:XS

#1873 Improved the documentation in the migration docs
  docs/howtos/migrations/migrate_from_v01_to_v02.md
Labels: size:S

#1872 docs: match default `timeout` in `RunConfig`
  src/ragas/run_config.py
Labels: size:XS

#1853 fix(prompt/mixin): Add name property and add it to saving/loading path.
  src/ragas/prompt/mixin.py
Labels: size:S

#1876 Adding missing evaluate import to evals guide
  docs/getstarted/evals.md
Labels: size:XS

#1877 Improve error message for missing embeddings in Answer Relevancy Metric
  src/ragas/metrics/_answer_relevance.py
  src/ragas/metrics/_answer_similarity.py
Labels: size:XS

#1879 Change the validate_samples functionality
  src/ragas/dataset_schema.py
Labels: size:XS

#1884 chore: added openhands for solving some github issues
  .github/workflows/openhands.yml
  src/ragas/dataset_schema.py
Labels: size:M

#1874 Faithfulness prompt update to avoid having single quotes in response
  src/ragas/prompt/pydantic_prompt.py
Labels: size:XS

#1886 Internal logging and tracing improvements.
  src/ragas/sdk.py
  src/ragas/utils.py
Labels: size:M

#1888 docs: added office hour links
  README.md
  docs/extra/overrides/main.html
  mkdocs.yml
Labels: size:M

#1883 added the end of sequence token for the WatsonX family of models
  src/ragas/llms/base.py
Labels: size:XS

#1878 Enhance langgraph integration to preserve metadata
  src/ragas/integrations/langgraph.py
Labels: size:M

#1887 Adding tutorial for Haystack Integration
  docs/howtos/integrations/_haystack.md
  docs/howtos/integrations/haystack.ipynb
  docs/howtos/integrations/haystack.md
  docs/howtos/integrations/index.md
  mkdocs.yml
Labels: size:XXL
