Repository explodinggradients/ragas, pull requests merged in 2025-05, with the labels that each got.

#2026 llamaindex agentic integration
  docs/howtos/integrations/amazon_bedrock.md
  docs/howtos/integrations/index.md
  docs/howtos/integrations/llamaindex_agents.md
  mkdocs.yml
  src/ragas/integrations/llama_index.py
  src/ragas/integrations/r2r.py
Labels: size:XL

#1991 Fix: Arbitrary File Read Vulnerability + Feat: Security settings
  src/ragas/prompt/multi_modal_prompt.py
Labels: size:L

#2039 feat: add devin's deepwiki
  .gitignore
  README.md
Labels: size:S
